In [4]:
#processed_company_df.csv

In [2]:
import pandas as pd
import numpy as np
import random

companies = pd.read_csv("../data/processed/processed_company_df.csv")#, index_col=False)
companies

,Unnamed: 0,company_name,permalink,founders,funding,jobs_created,age_years,founding_date,closing_date,category,ipo,city,region,patents,patent_confidence,city_and_state,county,metro
0,0,Resilio,/organizations/resiliohq,"['Anders SÃ¸ndergaard', 'Thomas Scherning', 'Je...",0,10.0,2.6274,2016-11-01,NaN,"['Education', 'Health Care', 'Computer', 'Soft...",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
1,1,Codementor,/organizations/codementor,['Weiting Liu'],3400000,50.0,6.4630,2013-01-01,NaN,"['Education', 'Web Development', 'Developer To...",0,Mountain View,California,0,NaN,"Mountain View, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
2,2,Smart MultiMedia,/organizations/smart-multimedia,NaN,0,50.0,12.4685,2007-01-01,NaN,"['Digital Media', 'Data Visualization', 'Consu...",0,Houston,Texas,0,NaN,"Houston, TX",Harris,"Houston-Sugar Land-Baytown, TX"
3,3,Evolution 2,/organizations/evolution-2-3,"['Konrad Kopczynski', 'Alika Graham']",0,10.0,2.7945,2016-09-01,NaN,"['Quantified Self', 'Personal Development', 'P...",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
4,4,Ultraprise Loan Technologies,/organizations/ultraprise-loan-technologies,NaN,9500000,NaN,18.4712,2001-01-01,NaN,"['E-Commerce', 'B2B']",0,Frederick,Maryland,0,NaN,"Frederick, MD",Frederick,"Winchester, VA-WV"
5,5,Workspace Property Trust,/organizations/workspace-property-trust,"['Roger Thomas', 'Leo Nolan', 'Thomas A. Rizk']",1275000000,250.0,4.4630,2015-01-01,NaN,['Real Estate'],0,Horsham,Pennsylvania,0,NaN,"Horsham, PA",Montgomery,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
6,6,86 Repairs,/organizations/86-repairs,"['Daniel Estrada', 'Joe Gallagher']",1500000,10.0,1.4603,2018-01-01,NaN,"['Restaurants', 'Software', 'Big Data', 'Predi...",0,Chicago,Illinois,0,NaN,"Chicago, IL",Cook,"Chicago-Naperville-Joliet, IL-IN-WI"
7,7,AKW Analytics Inc.,/organizations/akw-analytics-inc,NaN,0,10.0,5.6904,2013-10-10,NaN,"['Oil and Gas', 'Analytics', 'Big Data']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
8,8,myWebRoom,/organizations/mywebroom,"['Artem Fedyaev', 'John Gonzalez']",4300000,50.0,7.0493,2012-06-01,NaN,"['E-Commerce', 'Cloud Computing', 'Interior De...",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
9,9,"Trusted Translations, Inc.",/organizations/trusted-translations-inc,NaN,0,500.0,18.7151,2000-10-04,NaN,"['Translation Service', 'Document Management',...",0,Washington,District of Columbia,0,NaN,"Washington, DC",District of Columbia,"Washington-Arlington-Alexandria, DC-VA-MD-WV"
10,10,BioVigilant Systems,/organizations/biovigilant-systems,['Deward Manzer'],6700000,50.0,14.4685,2005-01-01,NaN,['Biotechnology'],0,Tucson,Arizona,4,2.0,"Tucson, AZ",Pima,"Tucson, AZ"
11,11,Fermata Energy,/organizations/fermata-energy,NaN,0,10.0,6.4630,2013-01-01,NaN,"['Energy', 'Electric Vehicle']",0,Charlottesville,Virginia,0,NaN,"Charlottesville, VA",Charlottesville,"Charlottesville, VA"
12,12,Net Aspects,/organizations/net-aspects,NaN,0,10.0,17.8904,2001-08-01,NaN,"['CRM', 'Web Development', 'SEO', 'SaaS', 'Sof...",0,Fairfield,California,0,NaN,"Fairfield, CA",Solano,"Vallejo-Fairfield, CA"
13,13,The Athletes Network,/organizations/the-athletes-network,"['Chris Dessi', 'Anthony Zarro']",0,10.0,4.7781,2011-01-01,2015-10-11,"['Education', 'Humanitarian', 'E-Commerce', 'S...",0,Tarrytown,New York,0,NaN,"Tarrytown, NY",Westchester,"New York-Newark-Jersey City, NY-NJ-PA"
14,14,LG DESIGN STONE,/organizations/lg-design-stone,NaN,0,10.0,14.3589,2005-02-10,NaN,"['Product Design', 'Real Estate', 'Manufacturi...",0,Shrewsbury,Massachusetts,0,NaN,"Shrewsbury, MA",Worcester,"Worcester, MA"
15,15,"OPUS Telehealth, LTD",/organizations/opus-telehealth-ltd,NaN,0,10.0,4.5479,2014-12-01,NaN,"['Health Care', 'Information Technology']",0,Los Angeles,California,0,NaN,"Los Angeles, CA",Los Angeles,"Los Angeles-Long Beach-Santa Ana, CA"
16,16,ZipHub,/organizations/ziphub,NaN,0,10.0,4.1342,2015-05-01,NaN,"['E-Commerce', 'Internet', 'Advertising']",0,Fort Worth,Texas,0,NaN,"Fort Worth, TX",Tarrant,"Dallas-Fort Worth-Arlington, TX"
17,17,AgShift,/organizations/agshift,['Miku Jha'],2000000,10.0,3.4630,2016-01-01,NaN,"['Software', 'Information Technology']",0,Santa Clara,California,0,NaN,"Santa Clara, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
18,18,Aclarity Systems,/organizations/aclarity-systems,NaN,0,50.0,8.1370,2011-05-01,NaN,"['Security', 'Information Technology']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
19,19,Bistro,/organizations/bistro,"['Zachary Flower', 'Andy Stone']",0,100.0,1.5890,2013-07-01,2015-02-01,"['Photography', 'Restaurants', 'Reputation', '...",0,Boulder,Colorado,0,NaN,"Boulder, CO",Boulder,"Boulder, CO"
20,20,Eligible,/organizations/eligible-api,"['Katelyn Gleason', 'Patrice Krakow', 'James S...",25200000,50.0,7.6055,2011-11-11,NaN,"['Developer APIs', 'Health Care', 'Information...",0,Brooklyn,New York,0,NaN,"Brooklyn, NY",Kings,"New York-Newark-Jersey City, NY-NJ-PA"
21,21,OffSiteNOC,/organizations/offsitenoc,NaN,0,50.0,10.7068,2008-10-05,NaN,"['SEO', 'Web Hosting', 'Information Services']",0,Lutherville Timonium,Maryland,0,NaN,"Lutherville Timonium, MD",Baltimore,"Baltimore-Towson, MD"
22,22,Nasdaq Private Market,/organizations/nasdaq-private-market,NaN,0,50.0,6.3014,2013-03-01,NaN,['Finance'],0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
23,23,Milkman SF,/organizations/milkman-sf,NaN,0,10.0,6.4630,2013-01-01,NaN,"['Food and Beverage', 'Agriculture']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
24,24,Termaxia,/organizations/termaxia,"['Boon Thau Loo', 'Changbin Liu']",150000,10.0,4.4630,2015-01-01,NaN,"['Big Data', 'Information Technology', 'Inform...",0,Philadelphia,Pennsylvania,0,NaN,"Philadelphia, PA",Philadelphia,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
25,25,IT'SUGAR,/organizations/itsugar,NaN,4000000,1000.0,13.4685,2006-01-01,NaN,"['Food and Beverage', 'E-Commerce', 'Food Proc...",0,Deerfield Beach,Florida,0,NaN,"Deerfield Beach, FL",Broward,"Miami-Fort Lauderdale-Pompano Beach, FL"
26,26,Samahope,/organizations/samahope,"['Leila Janah', 'Shivani Garg Patel']",0,50.0,7.9479,2011-07-09,NaN,"['Crowdfunding', 'Financial Services', 'Medical']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
27,27,InspiriaMedia Group,/organizations/inspiriamedia-group,NaN,0,50.0,15.4712,2004-01-01,NaN,"['Marketing', 'Advertising']",0,White Plains,New York,0,NaN,"White Plains, NY",Westchester,"New York-Newark-Jersey City, NY-NJ-PA"
28,28,Bright Power,/organizations/bright-power,['Jeffrey Perlman'],6826500,250.0,14.4795,2004-12-28,NaN,"['Energy', 'Energy Management', 'Solar']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
29,29,CloudAptitude,/organizations/cloudaptitude,['Clint Rosenblatt'],15000,10.0,7.3918,2012-01-28,NaN,"['Social Media', 'Software']",0,Memphis,Tennessee,0,NaN,"Memphis, TN",Shelby,"Memphis, TN-MS-AR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78903,78924,WSI Connect,/organizations/wsi-connect,NaN,0,50.0,7.4685,2012-01-01,NaN,"['Consulting', 'Marketing Automation']",0,Concord,California,0,NaN,"Concord, CA",Contra Costa,"San Francisco-Oakland-Hayward, CA"
78904,78925,FÃRIup,/organizations/f-riup,['Julius Niskey'],0,10.0,5.5507,2013-12-01,NaN,"['Fitness', 'Health Care', 'Advertising']",0,Las Vegas,Nevada,0,NaN,"Las Vegas, NV",Clark,"Las VegasâParadise, NV"
78905,78926,DBL Surety LLC,/organizations/dbl-surety,NaN,0,10.0,8.4685,2011-01-01,NaN,"['E-Commerce', 'Finance', 'Insurance']",0,Daytona Beach,Florida,0,NaN,"Daytona Beach, FL",Volusia,"Deltona-Daytona Beach-Ormond Beach, FL"
78906,78927,SteamChain,/organizations/steamchain,['Michael Cromheecke'],2790000,10.0,1.7096,2017-10-03,NaN,"['Blockchain', 'Machinery Manufacturing', 'Ind...",0,Grafton,Wisconsin,0,NaN,"Grafton, WI",Ozaukee,"Milwaukee-Waukesha-West Allis, WI"
78907,78928,UpDown,/organizations/updown,"['Michael Reich', 'Phuc Truong', 'Georg Ludvik...",1750000,10.0,12.2795,2007-03-12,NaN,"['Collaboration', 'Social Media', 'Financial S...",0,Cambridge,Massachusetts,0,NaN,"Cambridge, MA",Middlesex,"Boston-Cambridge-Newton, MA-NH"
78908,78929,eGainers,/organizations/egainers,['Massimo Colella'],0,50.0,7.2767,2012-03-11,NaN,['E-Commerce'],0,Miami Beach,Florida,0,NaN,"Miami Beach, FL",Miami-Dade,"Miami-Fort Lauderdale-Pompano Beach, FL"
78909,78930,Flow Kana,/organizations/flow-kana,"['Diego Zimet', 'Adam Steinberg', 'Michael Ste...",147500000,250.0,5.4658,2014-01-01,NaN,"['Agriculture', 'Cannabis', 'Farming']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
78910,78931,Imbria Pharmaceuticals,/organizations/imbria-pharmaceuticals,"['Andrew Levin', 'David-Alexandre Gros']",40249995,50.0,1.4630,2018-01-01,NaN,"['Pharmaceutical', 'Health Care', 'Biotechnolo...",0,Boston,Massachusetts,0,NaN,"Boston, MA",Suffolk,"Boston-Cambridge-Newton, MA-NH"
78911,78932,Teal,/organizations/teal,['George Matus'],13300000,50.0,5.4658,2014-01-01,NaN,"['Drones', 'Robotics', 'Product Design', 'Manu...",0,Salt Lake City,Utah,4,2.0,"Salt Lake City, UT",Salt Lake,"Salt Lake City, UT"
78912,78933,Eaglewood Capital Management,/organizations/eaglewood-capital-management,['Jon Barlow'],0,10.0,8.4685,2011-01-01,NaN,"['Peer to Peer', 'Lending', 'Financial Services']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
78913,78934,L7 Informatics,/organizations/l7-informatics,NaN,0,50.0,7.4685,2012-01-01,NaN,['Biotechnology'],0,Austin,Texas,0,NaN,"Austin, TX",Hays,"Austin-Round Rock, TX"
78914,78935,Healthtech Women,/organizations/healthtech-women,"['Carla Brenner', 'Aditi Deeg', 'Carla Brenner']",0,10.0,5.2192,2014-04-01,NaN,"['Health Care', 'Biotechnology']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
78915,78936,"VoiceAcuity, Inc",/organizations/voiceacuity-inc,NaN,0,10.0,2.4630,2017-01-01,NaN,[],0,Boston,Massachusetts,0,NaN,"Boston, MA",Suffolk,"Boston-Cambridge-Newton, MA-NH"
78916,78937,TimeBridge,/organizations/timebridge,"['Tsachy Shacham', 'Yori Nelken']",12400000,50.0,14.1425,2005-05-01,NaN,"['Collaboration', 'Meeting Software', 'Software']",0,Mountain View,California,0,NaN,"Mountain View, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
78917,78938,Wrap Technologies,/organizations/wrap-technologies,NaN,0,10.0,3.4658,2016-01-01,NaN,"['Security', 'Electronics']",0,Las Vegas,Nevada,4,2.0,"Las Vegas, NV",Clark,"Las VegasâParadise, NV"
78918,78939,Roomster,/organizations/roomster,"['Roman Zaks', 'John S. Shriber']",0,50.0,16.4740,2003-01-01,NaN,"['Android', 'Social Media', 'iOS', 'Marketplac...",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
78919,78940,Choice Career College,/organizations/choice-career-college,NaN,0,10.0,7.4685,2012-01-01,NaN,['Enterprise Software'],0,Des Plaines,Illinois,0,NaN,"Des Plaines, IL",Cook,"Chicago-Naperville-Joliet, IL-IN-WI"
78920,78941,Emerge,/organizations/emerging-1-inc-dba-emerge,['Leo Linder'],0,500.0,7.0521,2012-06-01,NaN,"['Business Development', 'Marketing', 'Sales',...",0,Rochester,New York,0,NaN,"Rochester, NY",Monroe,"Rochester, NY"
78921,78942,Big Couch Media Group,/organizations/big-couch-media-group,NaN,0,50.0,12.4712,2007-01-01,NaN,['Media and Entertainment'],0,Palm Beach,Florida,0,NaN,"Palm Beach, FL",Palm Beach,"Miami-Fort Lauderdale-Pompano Beach, FL"
78922,78943,"3D Travel, Inc",/organizations/3d-travel-inc,NaN,0,50.0,9.4685,2010-01-01,NaN,['Travel'],0,Los Gatos,California,0,NaN,"Los Gatos, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
78923,78944,OtherSide Entertainment,/organizations/otherside-entertainment,"['Warren Spector', 'Paul Neurath']",0,50.0,6.4658,2013-01-01,NaN,"['Video Games', 'Gaming']",0,Lincoln,Massachusetts,0,NaN,"Lincoln, MA",Middlesex,"Boston-Cambridge-Newton, MA-NH"
78924,78945,Koniag Information Security Services,/organizations/koniag-information-security-ser...,NaN,0,250.0,8.4685,2011-01-01,NaN,"['Cyber Security', 'Management Consulting']",0,Chantilly,Virginia,0,NaN,"Chantilly, VA",Fairfax,"Washington-Arlington-Alexandria, DC-VA-MD-WV"
78925,78946,"Strivr, Inc.",/organizations/strivr-inc,['Zach Gray'],0,10.0,5.4575,2014-01-04,NaN,"['Social Media', 'Lifestyle', 'Apps']",0,Livingston,New Jersey,0,NaN,"Livingston, NJ",Essex,"New York-Northern New Jersey-Long Island, NY-N..."
78926,78947,TripExpert,/organizations/tripexpert,"['Andrew Nicol', 'Emily Hughes']",0,10.0,6.4658,2013-01-01,NaN,"['Internet', 'Travel']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
78927,78948,Pyze,/organizations/pyze,"['John Chisholm', 'Dickey Singh', 'Prabhjot Si...",1700000,50.0,5.4658,2014-01-01,NaN,"['CRM', 'Internet', 'Advertising', 'Marketing ...",0,Redwood City,California,0,NaN,"Redwood City, CA",San Mateo,"San Francisco-Oakland-Hayward, CA"
78928,78949,OneRoof,/organizations/oneroof,['Miguel Ramilla'],3400000,50.0,14.4712,2005-01-01,NaN,['Non Profit'],0,Berkeley,California,0,NaN,"Berkeley, CA",Alameda,"San Francisco-Oakland-Hayward, CA"
78929,78950,Timefly,/organizations/timefly,NaN,0,10.0,5.4658,2014-01-01,NaN,"['Publishing', 'News']",0,Los Angeles,California,0,NaN,"Los Angeles, CA",Los Angeles,"Los Angeles-Long Beach-Santa Ana, CA"
78930,78951,EZ-AD TV,/organizations/ez-ad-tv,['Lawrence Mansour'],100000,10.0,5.6932,2013-10-10,NaN,"['Marketing', 'Advertising', 'Retail', 'Video']",0,Los Angeles,California,0,NaN,"Los Angeles, CA",Los Angeles,"Los Angeles-Long Beach-Santa Ana, CA"
78931,78952,Apropose,/organizations/apropose,"['Arvind Satyanarayan', 'Jerry Talton', 'Ranji...",1875000,50.0,2.2959,2013-09-15,2016-01-01,"['Analytics', 'Big Data']",0,Mountain View,California,0,NaN,"Mountain View, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
78932,78953,Scilex Pharmaceuticals,/organizations/scilex-pharmaceuticals,"['William Pedranti', 'Anthony P Mack']",7479930,10.0,7.4685,2012-01-01,NaN,"['Pharmaceutical', 'Health Care', 'Medical']",0,Malvern,Pennsylvania,0,NaN,"Malvern, PA",Chester,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"

In [3]:
companies.shape

(78933, 18)

In [3]:
companies.columns

Index(['Unnamed: 0', 'company_name', 'permalink', 'founders', 'funding',
       'jobs_created', 'age_years', 'founding_date', 'closing_date',
       'category', 'ipo', 'city', 'region', 'patents', 'patent_confidence',
       'city_and_state', 'county', 'metro'],
      dtype='object')

In [4]:
companies = companies[companies['founding_date'] > '2000-01-01']

In [5]:
companies_zero_funding_df = companies[(companies['jobs_created'] > 0) & (companies['patents'] > 0) & (companies['funding'] <= 0)]
companies_zero_funding_df = companies_zero_funding_df.reset_index(drop=True)
companies_zero_funding_df.shape

(1553, 18)

In [6]:
# Python code to generate 
# random numbers and 
# append them to a list 
import random 
  
# Function to generate 
# and append them  
# start = starting range, 
# end = ending range 
# num = number of  
# elements needs to be appended 
def Rand(start, end, num): 
    res = [] 
  
    for j in range(num): 
        res.append(random.randint(start, end)) 
  
    return res 
  
# Driver Code 
num = 30
start = 0
end = companies.shape[0]
randoms = (Rand(start, end, num)) 
print(randoms)

[48389, 40998, 19379, 52832, 32412, 49808, 31107, 28175, 28722, 59091, 10933, 9381, 14979, 9424, 12788, 55055, 56128, 56606, 41126, 31869, 22191, 36596, 43968, 63926, 6247, 26023, 78817, 43321, 3639, 27705]

In [7]:
zero = 0
for i in randoms:
    zero = zero + 1
    print(str(zero) + ' ' + str(companies.at[i, 'company_name']))
    print('\nCB')
    # + str(companies.at[i, 'jobs_created'])#, 'funding','jobs_created', 'age_years', 'founding_date'])
    print('founders: ' + str(companies.at[i, 'founders']))
    print('funding: ' + str(companies.at[i, 'funding']))
    print('IPO: ' + str(companies.at[i, 'ipo']))   
    print('jobs created: ' + str(companies.at[i, 'jobs_created']))
    print('city: ' + str(companies.at[i, 'city']))
    print('\nPB \nfounders: \nfunding: \njobs: \n \nMM \nfounders: \nfunding: \njobs: \n \n')
    
    print('------- \n')
    
#     if companies.at[i, 'founders'] is not None:
#         print(companies.at[i, 'founders'])

1 Hydril

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Houston

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

2 5nine Software

CB
founders: nan
funding: 0
IPO: 0
jobs created: 250.0
city: West Palm Beach

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

3 Canna Energy

CB
founders: nan
funding: 0
IPO: 0
jobs created: 50.0
city: Atlanta

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

4 Peer2Peer Tutor

CB
founders: ['Erik Kimel']
funding: 0
IPO: 0
jobs created: 100.0
city: New York

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

5 ScholarBuys

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Carpentersville

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

6 pear.ai

CB
founders: ['Peter Shiau', 'Sukhjinder Singh', 'Christopher McLachlan PhD']
funding: 0
IPO: 0
jobs created: 10.0
city: San Francisco

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

7 NBA Math Hoops

CB
founders: ['Khalil Fuller']
funding: 50000
IPO: 0
jobs created: 10.0
city: Denver

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

8 ITM Mobile

CB
founders: ['thomas hallin', 'ita grossman']
funding: 0
IPO: 0
jobs created: 10.0
city: Apple Valley

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

9 The Runner's Band

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Folsom

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

10 NASDAQ Entrepreneurial Center

CB
founders: nan
funding: 0
IPO: 0
jobs created: 50.0
city: San Francisco

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

11 Stay at Home Personal Care

CB
founders: nan
funding: 0
IPO: 0
jobs created: 250.0
city: Charlottesville

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

12 Tip'd

CB
founders: ['Andy Hagans', 'Jimmy Atkinson']
funding: 0
IPO: 0
jobs created: 10.0
city: Houston

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

13 TravelTipping

CB
founders: ['Scott Blankenship']
funding: 0
IPO: 0
jobs created: 10.0
city: San Francisco

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

14 The Research Valley Innovation Center

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: College Station

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

15 EcoFactor

CB
founders: ['Leo Cheung', 'Scott Hublou', 'John Steinberg']
funding: 31000000
IPO: 0
jobs created: 50.0
city: Redwood City

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

16 Hiptest

CB
founders: ['Laurent PY']
funding: 0
IPO: 0
jobs created: 50.0
city: San Francisco

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

17 FLoT Systems

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Boulder

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

18 10 Best SEO

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: San Francisco

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

19 High Side Solutions

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Laurel

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

20 Hoopstop

CB
founders: ['Lanier Brown']
funding: 0
IPO: 0
jobs created: 10.0
city: Los Angeles

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

21 Cleveland International Fund(CiF)

CB
founders: nan
funding: 0
IPO: 0
jobs created: 50.0
city: Cleveland

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

22 3rd Rock Sunblock

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Virginia Beach

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

23 Arlo Labs

CB
founders: ['Carolyn Hou']
funding: 0
IPO: 0
jobs created: 10.0
city: New York

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

24 C-Vision

CB
founders: ['Venkata Eragam']
funding: 0
IPO: 0
jobs created: 100.0
city: Troy

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

25 Solve Advisors

CB
founders: ['Eugene Grinberg']
funding: 0
IPO: 0
jobs created: 50.0
city: Rockville Centre

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

26 Internet Television Solutions

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Ellicott City

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

27 EngenuitySC

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Columbia

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

28 iMovR

CB
founders: ['Andy Rosenbaum', 'Ron Wiener']
funding: 224000
IPO: 0
jobs created: 50.0
city: Bellevue

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

29 Fullbridge

CB
founders: ['Peter Olson', 'Candice Olson']
funding: 27900048
IPO: 0
jobs created: 50.0
city: Boston

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

30 Gracious Bridal

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Austin

PB
founders:
funding:
jobs:

MM
founders:
funding:
jobs:


-------

In [8]:
[52200, 51630, 8499, 56903, 29392, 58194, 54985, 65137, 45623, 7553, 37795, 15499, 58623, 4306, 61683, 41927, 46359, 17862, 67222, 19616, 47753, 55389, 26701, 52676, 36865, 63183, 48723, 20097, 60864, 23797]

[52200,
 51630,
 8499,
 56903,
 29392,
 58194,
 54985,
 65137,
 45623,
 7553,
 37795,
 15499,
 58623,
 4306,
 61683,
 41927,
 46359,
 17862,
 67222,
 19616,
 47753,
 55389,
 26701,
 52676,
 36865,
 63183,
 48723,
 20097,
 60864,
 23797]

In [9]:
under_1 = companies[companies['funding'] < 1000]

In [10]:
under_1.shape

(52987, 18)

In [11]:
under_1 = under_1.reset_index(drop=True)

In [12]:
under_0 = companies[companies['funding'] == 0]
under_0.shape

(52987, 18)

In [13]:
btw_1_and_10 = companies[(companies['funding'] >= 1000) & (companies['funding'] <= 10000)]
btw_1_and_10 = btw_1_and_10.reset_index(drop=True)
btw_1_and_10.shape

(310, 18)

In [14]:
under_10 = companies[companies['funding'] < 10000]
under_10.shape

(53173, 18)

` companies_zero_funding_df `

In [15]:
btw_10_and_100 = companies[(companies['funding'] >= 10000) & (companies['funding'] <= 100000)]
btw_10_and_100 = btw_10_and_100.reset_index(drop=True)
btw_10_and_100.shape

(2812, 18)

In [16]:
btw_100_and_1_mil = companies[(companies['funding'] > 100000) & (companies['funding'] < 1000000)]
btw_100_and_1_mil = btw_100_and_1_mil.reset_index(drop=True)
btw_100_and_1_mil.shape

(6025, 18)

In [17]:
btw_1_mil_and_10_mil = companies[(companies['funding'] >= 1000000) & (companies['funding'] < 10000000)]
btw_1_mil_and_10_mil = btw_1_mil_and_10_mil.reset_index(drop=True)
btw_1_mil_and_10_mil.shape

(9717, 18)

In [18]:
over_10_mil = companies[(companies['funding'] >= 10000000)]
over_10_mil.shape
over_10_mil = over_10_mil.reset_index(drop=True)

In [19]:
def find_randoms(companies, zero):

    # Driver Code 
    num = 6
    start = 0
    end = companies.shape[0]

    def Rand(start, end, num): 
        res = [] 

        for j in range(num): 
            res.append(random.randint(start, end)) 

        return res 

    randoms = Rand(start, end, num)
    for i in randoms:
        zero = zero + 1
        print(str(zero) + ' ' + str(companies.at[i, 'company_name']))
        print('\nCB')
        # + str(companies.at[i, 'jobs_created'])#, 'funding','jobs_created', 'age_years', 'founding_date'])
        print('founders: ' + str(companies.at[i, 'founders']))
        print('funding: ' + str(companies.at[i, 'funding']))
        print('IPO: ' + str(companies.at[i, 'ipo']))   
        print('jobs created: ' + str(companies.at[i, 'jobs_created']))
        
        print('city: ' + str(companies.at[i, 'city']))
        print('\nPB \nfounders: \nfunding: \nemployees: \n \nMM \nfounders: \nfunding: \nemployees: \n \n')
        
    

        print('------- \n')

In [20]:
random1 = (Rand(0, 53173, 6))
random1

[25360, 210, 22386, 49780, 632, 39820]

In [21]:
find_randoms(companies_zero_funding_df, 0)

1 Accelrys

CB
founders: nan
funding: 0
IPO: 1
jobs created: 1000.0
city: San Diego

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

2 Elastic

CB
founders: ['Steli Efti', 'Thomas Steinacher']
funding: 0
IPO: 0
jobs created: 500.0
city: Mountain View

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

3 Triggerfinger Software

CB
founders: nan
funding: 0
IPO: 0
jobs created: 10.0
city: Portland

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

4 Savannah River Nuclear Solutions

CB
founders: nan
funding: 0
IPO: 0
jobs created: 1000000.0
city: Aiken

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

5 Voice Carrier

CB
founders: nan
funding: 0
IPO: 0
jobs created: 50.0
city: San Jose

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

6 Typenex Medical

CB
founders: nan
funding: 0
IPO: 0
jobs created: 50.0
city: Chicago

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

In [22]:
find_randoms(btw_10_and_100, 6)

7 Wellness Corner

CB
founders: nan
funding: 48000
IPO: 0
jobs created: nan
city: Prairieville

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

8 Lilikoi

CB
founders: nan
funding: 10000
IPO: 0
jobs created: nan
city: Kahuku

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

9 MashMango

CB
founders: ['Dave Lee', 'Dah-Yoh Lim']
funding: 100000
IPO: 0
jobs created: 10.0
city: Boston

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

10 Yovigo

CB
founders: ['Tyson Crandall', 'Ryan Pfleger', 'Brandon Swift']
funding: 45000
IPO: 0
jobs created: 10.0
city: Santa Barbara

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

11 WorkHands

CB
founders: ['James Dunbar', 'Paul Zaich']
funding: 20000
IPO: 0
jobs created: 50.0
city: San Francisco

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

12 Farm Tech Innovation

CB
founders: ['Barry Beverly']
funding: 100000
IPO: 0
jobs created: 10.0
city: Fort Worth

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

In [23]:
find_randoms(btw_100_and_1_mil, 12)

13 Delta Plant Technologies

CB
founders: nan
funding: 324942
IPO: 0
jobs created: nan
city: Akron

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

14 SiggPay INC

CB
founders: ['Brian Fuller']
funding: 615000
IPO: 0
jobs created: 50.0
city: Norwalk

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

15 BeckonCall

CB
founders: ['Jeffrey Becker']
funding: 300000
IPO: 0
jobs created: 10.0
city: Scottsdale

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

16 FoodSquire

CB
founders: ['Joe Capone']
funding: 200000
IPO: 0
jobs created: 50.0
city: Marshfield

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

17 Leonid Systems

CB
founders: ['Alex Cowan']
funding: 250000
IPO: 0
jobs created: 100.0
city: Gaithersburg

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

18 Freeing Returns

CB
founders: ['Charlotte Mattier', 'Lisette Rice', 'Barbara Jones']
funding: 175000
IPO: 0
jobs created: nan
city: Atlanta

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

In [24]:
find_randoms(btw_1_mil_and_10_mil, 18)

19 DataRPM Corporation

CB
founders: ['Sundeep Sanghavi', 'Ruban Phukan', 'Gautam Shyamantak']
funding: 5900000
IPO: 0
jobs created: 50.0
city: Redwood City

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

20 AtYourGate

CB
founders: ['PJ Mastracchio']
funding: 2000000
IPO: 0
jobs created: 10.0
city: San Diego

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

21 Healthspek

CB
founders: ['Randy Farr', 'Bruce LeFew']
funding: 1250000
IPO: 0
jobs created: 50.0
city: Nashville

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

22 Dreamware

CB
founders: ['Nicholas Nicholas Anagnostou', 'Bryan Harmon']
funding: 6983000
IPO: 0
jobs created: 10.0
city: Naples

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

23 Lifeguard Health Networks

CB
founders: ['Danielle Guttman Klein', 'Michael Helfrich', 'Martin Carty']
funding: 2650000
IPO: 0
jobs created: 50.0
city: Wayne

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

24 Acompli

CB
founders: ['JJ Zhuang', 'Javier Soltero', 'Kevin Henrikson']
funding: 7300000
IPO: 0
jobs created: 50.0
city: San Francisco

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

In [25]:
find_randoms(over_10_mil, 24)

25 Kapow Software

CB
founders: ['Stefan Andreasen']
funding: 19747982
IPO: 0
jobs created: 10000.0
city: Palo Alto

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

26 Xirrus

CB
founders: ['Dirk I. Gates', 'Patrick Parker', 'Steven F. DeGennaro', 'Dirk Gates']
funding: 120223562
IPO: 0
jobs created: 250.0
city: Thousand Oaks

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

27 Stackify

CB
founders: ['Matt Watson']
funding: 16251733
IPO: 0
jobs created: 50.0
city: Leawood

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

28 TravelBank

CB
founders: ['Reid Williams', 'Duke Chung', 'Ching-Ho Fung']
funding: 35000000
IPO: 0
jobs created: 50.0
city: San Francisco

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

29 InAuth

CB
founders: ['Paul Marsolan', 'Mike Patterson']
funding: 30752124
IPO: 0
jobs created: 250.0
city: Boston

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

30 Everest Infrastructure Partners

CB
founders: ['Mike Mackey', 'John Lemmon', 'Matt Newton']
funding: 100000000
IPO: 0
jobs created: 50.0
city: Pittsburgh

PB
founders:
funding:
employees:

MM
founders:
funding:
employees:


-------

In [26]:
#shift = companies.at['Shift', 'company']

companies

In [29]:
companies

,Unnamed: 0,company_name,permalink,founders,funding,jobs_created,age_years,founding_date,closing_date,category,ipo,city,region,patents,patent_confidence,city_and_state,county,metro
0,0,Resilio,/organizations/resiliohq,"['Anders SÃ¸ndergaard', 'Thomas Scherning', 'Je...",0,10.0,2.6274,2016-11-01,NaN,"['Education', 'Health Care', 'Computer', 'Soft...",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
1,1,Codementor,/organizations/codementor,['Weiting Liu'],3400000,50.0,6.4630,2013-01-01,NaN,"['Education', 'Web Development', 'Developer To...",0,Mountain View,California,0,NaN,"Mountain View, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
2,2,Smart MultiMedia,/organizations/smart-multimedia,NaN,0,50.0,12.4685,2007-01-01,NaN,"['Digital Media', 'Data Visualization', 'Consu...",0,Houston,Texas,0,NaN,"Houston, TX",Harris,"Houston-Sugar Land-Baytown, TX"
3,3,Evolution 2,/organizations/evolution-2-3,"['Konrad Kopczynski', 'Alika Graham']",0,10.0,2.7945,2016-09-01,NaN,"['Quantified Self', 'Personal Development', 'P...",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
4,4,Ultraprise Loan Technologies,/organizations/ultraprise-loan-technologies,NaN,9500000,NaN,18.4712,2001-01-01,NaN,"['E-Commerce', 'B2B']",0,Frederick,Maryland,0,NaN,"Frederick, MD",Frederick,"Winchester, VA-WV"
5,5,Workspace Property Trust,/organizations/workspace-property-trust,"['Roger Thomas', 'Leo Nolan', 'Thomas A. Rizk']",1275000000,250.0,4.4630,2015-01-01,NaN,['Real Estate'],0,Horsham,Pennsylvania,0,NaN,"Horsham, PA",Montgomery,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
6,6,86 Repairs,/organizations/86-repairs,"['Daniel Estrada', 'Joe Gallagher']",1500000,10.0,1.4603,2018-01-01,NaN,"['Restaurants', 'Software', 'Big Data', 'Predi...",0,Chicago,Illinois,0,NaN,"Chicago, IL",Cook,"Chicago-Naperville-Joliet, IL-IN-WI"
7,7,AKW Analytics Inc.,/organizations/akw-analytics-inc,NaN,0,10.0,5.6904,2013-10-10,NaN,"['Oil and Gas', 'Analytics', 'Big Data']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
8,8,myWebRoom,/organizations/mywebroom,"['Artem Fedyaev', 'John Gonzalez']",4300000,50.0,7.0493,2012-06-01,NaN,"['E-Commerce', 'Cloud Computing', 'Interior De...",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
9,9,"Trusted Translations, Inc.",/organizations/trusted-translations-inc,NaN,0,500.0,18.7151,2000-10-04,NaN,"['Translation Service', 'Document Management',...",0,Washington,District of Columbia,0,NaN,"Washington, DC",District of Columbia,"Washington-Arlington-Alexandria, DC-VA-MD-WV"
10,10,BioVigilant Systems,/organizations/biovigilant-systems,['Deward Manzer'],6700000,50.0,14.4685,2005-01-01,NaN,['Biotechnology'],0,Tucson,Arizona,4,2.0,"Tucson, AZ",Pima,"Tucson, AZ"
11,11,Fermata Energy,/organizations/fermata-energy,NaN,0,10.0,6.4630,2013-01-01,NaN,"['Energy', 'Electric Vehicle']",0,Charlottesville,Virginia,0,NaN,"Charlottesville, VA",Charlottesville,"Charlottesville, VA"
12,12,Net Aspects,/organizations/net-aspects,NaN,0,10.0,17.8904,2001-08-01,NaN,"['CRM', 'Web Development', 'SEO', 'SaaS', 'Sof...",0,Fairfield,California,0,NaN,"Fairfield, CA",Solano,"Vallejo-Fairfield, CA"
13,13,The Athletes Network,/organizations/the-athletes-network,"['Chris Dessi', 'Anthony Zarro']",0,10.0,4.7781,2011-01-01,2015-10-11,"['Education', 'Humanitarian', 'E-Commerce', 'S...",0,Tarrytown,New York,0,NaN,"Tarrytown, NY",Westchester,"New York-Newark-Jersey City, NY-NJ-PA"
14,14,LG DESIGN STONE,/organizations/lg-design-stone,NaN,0,10.0,14.3589,2005-02-10,NaN,"['Product Design', 'Real Estate', 'Manufacturi...",0,Shrewsbury,Massachusetts,0,NaN,"Shrewsbury, MA",Worcester,"Worcester, MA"
15,15,"OPUS Telehealth, LTD",/organizations/opus-telehealth-ltd,NaN,0,10.0,4.5479,2014-12-01,NaN,"['Health Care', 'Information Technology']",0,Los Angeles,California,0,NaN,"Los Angeles, CA",Los Angeles,"Los Angeles-Long Beach-Santa Ana, CA"
16,16,ZipHub,/organizations/ziphub,NaN,0,10.0,4.1342,2015-05-01,NaN,"['E-Commerce', 'Internet', 'Advertising']",0,Fort Worth,Texas,0,NaN,"Fort Worth, TX",Tarrant,"Dallas-Fort Worth-Arlington, TX"
17,17,AgShift,/organizations/agshift,['Miku Jha'],2000000,10.0,3.4630,2016-01-01,NaN,"['Software', 'Information Technology']",0,Santa Clara,California,0,NaN,"Santa Clara, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
18,18,Aclarity Systems,/organizations/aclarity-systems,NaN,0,50.0,8.1370,2011-05-01,NaN,"['Security', 'Information Technology']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
19,19,Bistro,/organizations/bistro,"['Zachary Flower', 'Andy Stone']",0,100.0,1.5890,2013-07-01,2015-02-01,"['Photography', 'Restaurants', 'Reputation', '...",0,Boulder,Colorado,0,NaN,"Boulder, CO",Boulder,"Boulder, CO"
20,20,Eligible,/organizations/eligible-api,"['Katelyn Gleason', 'Patrice Krakow', 'James S...",25200000,50.0,7.6055,2011-11-11,NaN,"['Developer APIs', 'Health Care', 'Information...",0,Brooklyn,New York,0,NaN,"Brooklyn, NY",Kings,"New York-Newark-Jersey City, NY-NJ-PA"
21,21,OffSiteNOC,/organizations/offsitenoc,NaN,0,50.0,10.7068,2008-10-05,NaN,"['SEO', 'Web Hosting', 'Information Services']",0,Lutherville Timonium,Maryland,0,NaN,"Lutherville Timonium, MD",Baltimore,"Baltimore-Towson, MD"
22,22,Nasdaq Private Market,/organizations/nasdaq-private-market,NaN,0,50.0,6.3014,2013-03-01,NaN,['Finance'],0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
23,23,Milkman SF,/organizations/milkman-sf,NaN,0,10.0,6.4630,2013-01-01,NaN,"['Food and Beverage', 'Agriculture']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
24,24,Termaxia,/organizations/termaxia,"['Boon Thau Loo', 'Changbin Liu']",150000,10.0,4.4630,2015-01-01,NaN,"['Big Data', 'Information Technology', 'Inform...",0,Philadelphia,Pennsylvania,0,NaN,"Philadelphia, PA",Philadelphia,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
25,25,IT'SUGAR,/organizations/itsugar,NaN,4000000,1000.0,13.4685,2006-01-01,NaN,"['Food and Beverage', 'E-Commerce', 'Food Proc...",0,Deerfield Beach,Florida,0,NaN,"Deerfield Beach, FL",Broward,"Miami-Fort Lauderdale-Pompano Beach, FL"
26,26,Samahope,/organizations/samahope,"['Leila Janah', 'Shivani Garg Patel']",0,50.0,7.9479,2011-07-09,NaN,"['Crowdfunding', 'Financial Services', 'Medical']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
27,27,InspiriaMedia Group,/organizations/inspiriamedia-group,NaN,0,50.0,15.4712,2004-01-01,NaN,"['Marketing', 'Advertising']",0,White Plains,New York,0,NaN,"White Plains, NY",Westchester,"New York-Newark-Jersey City, NY-NJ-PA"
28,28,Bright Power,/organizations/bright-power,['Jeffrey Perlman'],6826500,250.0,14.4795,2004-12-28,NaN,"['Energy', 'Energy Management', 'Solar']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
29,29,CloudAptitude,/organizations/cloudaptitude,['Clint Rosenblatt'],15000,10.0,7.3918,2012-01-28,NaN,"['Social Media', 'Software']",0,Memphis,Tennessee,0,NaN,"Memphis, TN",Shelby,"Memphis, TN-MS-AR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78903,78924,WSI Connect,/organizations/wsi-connect,NaN,0,50.0,7.4685,2012-01-01,NaN,"['Consulting', 'Marketing Automation']",0,Concord,California,0,NaN,"Concord, CA",Contra Costa,"San Francisco-Oakland-Hayward, CA"
78904,78925,FÃRIup,/organizations/f-riup,['Julius Niskey'],0,10.0,5.5507,2013-12-01,NaN,"['Fitness', 'Health Care', 'Advertising']",0,Las Vegas,Nevada,0,NaN,"Las Vegas, NV",Clark,"Las VegasâParadise, NV"
78905,78926,DBL Surety LLC,/organizations/dbl-surety,NaN,0,10.0,8.4685,2011-01-01,NaN,"['E-Commerce', 'Finance', 'Insurance']",0,Daytona Beach,Florida,0,NaN,"Daytona Beach, FL",Volusia,"Deltona-Daytona Beach-Ormond Beach, FL"
78906,78927,SteamChain,/organizations/steamchain,['Michael Cromheecke'],2790000,10.0,1.7096,2017-10-03,NaN,"['Blockchain', 'Machinery Manufacturing', 'Ind...",0,Grafton,Wisconsin,0,NaN,"Grafton, WI",Ozaukee,"Milwaukee-Waukesha-West Allis, WI"
78907,78928,UpDown,/organizations/updown,"['Michael Reich', 'Phuc Truong', 'Georg Ludvik...",1750000,10.0,12.2795,2007-03-12,NaN,"['Collaboration', 'Social Media', 'Financial S...",0,Cambridge,Massachusetts,0,NaN,"Cambridge, MA",Middlesex,"Boston-Cambridge-Newton, MA-NH"
78908,78929,eGainers,/organizations/egainers,['Massimo Colella'],0,50.0,7.2767,2012-03-11,NaN,['E-Commerce'],0,Miami Beach,Florida,0,NaN,"Miami Beach, FL",Miami-Dade,"Miami-Fort Lauderdale-Pompano Beach, FL"
78909,78930,Flow Kana,/organizations/flow-kana,"['Diego Zimet', 'Adam Steinberg', 'Michael Ste...",147500000,250.0,5.4658,2014-01-01,NaN,"['Agriculture', 'Cannabis', 'Farming']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
78910,78931,Imbria Pharmaceuticals,/organizations/imbria-pharmaceuticals,"['Andrew Levin', 'David-Alexandre Gros']",40249995,50.0,1.4630,2018-01-01,NaN,"['Pharmaceutical', 'Health Care', 'Biotechnolo...",0,Boston,Massachusetts,0,NaN,"Boston, MA",Suffolk,"Boston-Cambridge-Newton, MA-NH"
78911,78932,Teal,/organizations/teal,['George Matus'],13300000,50.0,5.4658,2014-01-01,NaN,"['Drones', 'Robotics', 'Product Design', 'Manu...",0,Salt Lake City,Utah,4,2.0,"Salt Lake City, UT",Salt Lake,"Salt Lake City, UT"
78912,78933,Eaglewood Capital Management,/organizations/eaglewood-capital-management,['Jon Barlow'],0,10.0,8.4685,2011-01-01,NaN,"['Peer to Peer', 'Lending', 'Financial Services']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
78913,78934,L7 Informatics,/organizations/l7-informatics,NaN,0,50.0,7.4685,2012-01-01,NaN,['Biotechnology'],0,Austin,Texas,0,NaN,"Austin, TX",Hays,"Austin-Round Rock, TX"
78914,78935,Healthtech Women,/organizations/healthtech-women,"['Carla Brenner', 'Aditi Deeg', 'Carla Brenner']",0,10.0,5.2192,2014-04-01,NaN,"['Health Care', 'Biotechnology']",0,San Francisco,California,0,NaN,"San Francisco, CA",San Francisco,"San Francisco-Oakland-Hayward, CA"
78915,78936,"VoiceAcuity, Inc",/organizations/voiceacuity-inc,NaN,0,10.0,2.4630,2017-01-01,NaN,[],0,Boston,Massachusetts,0,NaN,"Boston, MA",Suffolk,"Boston-Cambridge-Newton, MA-NH"
78916,78937,TimeBridge,/organizations/timebridge,"['Tsachy Shacham', 'Yori Nelken']",12400000,50.0,14.1425,2005-05-01,NaN,"['Collaboration', 'Meeting Software', 'Software']",0,Mountain View,California,0,NaN,"Mountain View, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
78917,78938,Wrap Technologies,/organizations/wrap-technologies,NaN,0,10.0,3.4658,2016-01-01,NaN,"['Security', 'Electronics']",0,Las Vegas,Nevada,4,2.0,"Las Vegas, NV",Clark,"Las VegasâParadise, NV"
78918,78939,Roomster,/organizations/roomster,"['Roman Zaks', 'John S. Shriber']",0,50.0,16.4740,2003-01-01,NaN,"['Android', 'Social Media', 'iOS', 'Marketplac...",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
78919,78940,Choice Career College,/organizations/choice-career-college,NaN,0,10.0,7.4685,2012-01-01,NaN,['Enterprise Software'],0,Des Plaines,Illinois,0,NaN,"Des Plaines, IL",Cook,"Chicago-Naperville-Joliet, IL-IN-WI"
78920,78941,Emerge,/organizations/emerging-1-inc-dba-emerge,['Leo Linder'],0,500.0,7.0521,2012-06-01,NaN,"['Business Development', 'Marketing', 'Sales',...",0,Rochester,New York,0,NaN,"Rochester, NY",Monroe,"Rochester, NY"
78921,78942,Big Couch Media Group,/organizations/big-couch-media-group,NaN,0,50.0,12.4712,2007-01-01,NaN,['Media and Entertainment'],0,Palm Beach,Florida,0,NaN,"Palm Beach, FL",Palm Beach,"Miami-Fort Lauderdale-Pompano Beach, FL"
78922,78943,"3D Travel, Inc",/organizations/3d-travel-inc,NaN,0,50.0,9.4685,2010-01-01,NaN,['Travel'],0,Los Gatos,California,0,NaN,"Los Gatos, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
78923,78944,OtherSide Entertainment,/organizations/otherside-entertainment,"['Warren Spector', 'Paul Neurath']",0,50.0,6.4658,2013-01-01,NaN,"['Video Games', 'Gaming']",0,Lincoln,Massachusetts,0,NaN,"Lincoln, MA",Middlesex,"Boston-Cambridge-Newton, MA-NH"
78924,78945,Koniag Information Security Services,/organizations/koniag-information-security-ser...,NaN,0,250.0,8.4685,2011-01-01,NaN,"['Cyber Security', 'Management Consulting']",0,Chantilly,Virginia,0,NaN,"Chantilly, VA",Fairfax,"Washington-Arlington-Alexandria, DC-VA-MD-WV"
78925,78946,"Strivr, Inc.",/organizations/strivr-inc,['Zach Gray'],0,10.0,5.4575,2014-01-04,NaN,"['Social Media', 'Lifestyle', 'Apps']",0,Livingston,New Jersey,0,NaN,"Livingston, NJ",Essex,"New York-Northern New Jersey-Long Island, NY-N..."
78926,78947,TripExpert,/organizations/tripexpert,"['Andrew Nicol', 'Emily Hughes']",0,10.0,6.4658,2013-01-01,NaN,"['Internet', 'Travel']",0,New York,New York,0,NaN,"New York, NY",New York,"New York-Newark-Jersey City, NY-NJ-PA"
78927,78948,Pyze,/organizations/pyze,"['John Chisholm', 'Dickey Singh', 'Prabhjot Si...",1700000,50.0,5.4658,2014-01-01,NaN,"['CRM', 'Internet', 'Advertising', 'Marketing ...",0,Redwood City,California,0,NaN,"Redwood City, CA",San Mateo,"San Francisco-Oakland-Hayward, CA"
78928,78949,OneRoof,/organizations/oneroof,['Miguel Ramilla'],3400000,50.0,14.4712,2005-01-01,NaN,['Non Profit'],0,Berkeley,California,0,NaN,"Berkeley, CA",Alameda,"San Francisco-Oakland-Hayward, CA"
78929,78950,Timefly,/organizations/timefly,NaN,0,10.0,5.4658,2014-01-01,NaN,"['Publishing', 'News']",0,Los Angeles,California,0,NaN,"Los Angeles, CA",Los Angeles,"Los Angeles-Long Beach-Santa Ana, CA"
78930,78951,EZ-AD TV,/organizations/ez-ad-tv,['Lawrence Mansour'],100000,10.0,5.6932,2013-10-10,NaN,"['Marketing', 'Advertising', 'Retail', 'Video']",0,Los Angeles,California,0,NaN,"Los Angeles, CA",Los Angeles,"Los Angeles-Long Beach-Santa Ana, CA"
78931,78952,Apropose,/organizations/apropose,"['Arvind Satyanarayan', 'Jerry Talton', 'Ranji...",1875000,50.0,2.2959,2013-09-15,2016-01-01,"['Analytics', 'Big Data']",0,Mountain View,California,0,NaN,"Mountain View, CA",Santa Clara,"San Jose-Sunnyvale-Santa Clara, CA"
78932,78953,Scilex Pharmaceuticals,/organizations/scilex-pharmaceuticals,"['William Pedranti', 'Anthony P Mack']",7479930,10.0,7.4685,2012-01-01,NaN,"['Pharmaceutical', 'Health Care', 'Medical']",0,Malvern,Pennsylvania,0,NaN,"Malvern, PA",Chester,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"

In [41]:
companies[companies['company_name'] == 'Shift']

,Unnamed: 0,company_name,permalink,founders,funding,jobs_created,age_years,founding_date,closing_date,category,ipo,city,region,patents,patent_confidence,city_and_state,county,metro
52200,52212,BrewDrop,/organizations/brewdrop,NaN,0,50.0,6.4658,2013-01-01,NaN,"['Craft Beer', 'Delivery', 'Apps', 'Wine And S...",0,Austin,Texas,0,NaN,"Austin, TX",Hays,"Austin-Round Rock, TX"

In [39]:
companies.at[11635, 'founders']

"['George Arison', 'Christian Ohler', 'Minnie Ingersoll', 'Morgan Knutson']"

In [54]:
companies[companies['company_name'] == 'BrewDrop']

,Unnamed: 0,company_name,permalink,founders,funding,jobs_created,age_years,founding_date,closing_date,category,ipo,city,region,patents,patent_confidence,city_and_state,county,metro
52200,52212,BrewDrop,/organizations/brewdrop,NaN,0,50.0,6.4658,2013-01-01,NaN,"['Craft Beer', 'Delivery', 'Apps', 'Wine And S...",0,Austin,Texas,0,NaN,"Austin, TX",Hays,"Austin-Round Rock, TX"

In [45]:
companies.shape

(78933, 18)