In [1]:
from pathlib import Path
import os

PROJ_ROOT = Path().resolve().parent
KEYS_DIR = PROJ_ROOT / 'keys' 
keys = KEYS_DIR / 'socos-quickstep-601-403a611fa9db.json'

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = str(keys)

In [2]:
    # PROCESS
    # 1. Extract tables from Big Query using a JOIN SQL query - combining the Binary Answers on the 'names' with the Questions
    #  - it is important to NOT use the Learner information from the JiveLearner to create a 'Learner' dataframe, because it results in fewer data points. Instead use a multiple-join
    # 2. Read in the data as a dateframe
    # 4. Process the data by:
    #     - choosing the last modified
    #     - eliminate duplicates
    # 5. create a new dataframe which has the Learners as the index and Questions as columns
    #     - encode the categorical answers numerically (-2, -1, 0, 1, 2)
    #     - changing the answers to overwrite based on the most definitive (highest or lowest) number
    # 4. export the table to bigquery
    #     - None / NaN BQ datatype

    # TOP QUESTIONS FOR TROUBLESHOOTING
    # Q 371: "Do you work outside of the home?" | 2,012
    # Q 367: "Does {kid_name} attend school outside of the home?" | 1,349
    # Q 368: "Do you have reliable childcare for {kid_name}?" | 1,216
    # Q 24: "Do you know the name of {kid_name}'s primary doctor?" | 350
    # Q 13: "Do you know your next door neighbor's first name?" | 341
    # Q 25: "Does your family have health care?" | 339
    # Q 18: "Does your spouse work multiple jobs?" | 335
    # Q 590: "Do you have a primary doctor?" | 325
    # Q 15: "Does your spouse work full-time?" | 318
    # Q 41: "Are you the first person in your family to graduate college?" | 314

    # LIST OF POSSIBLE ANSWERS
    # {'Dislike',
    #  "Doesn't apply",
    #  'Kid is too old',
    #  'Kid is too young',
    #  'No',
    #  'Not sure',
    #  'Yes',
    #  'absolutely',
    #  'abstract',
    #  'barely',
    #  'definitely',
    #  "doesn't apply",
    #  'good idea',
    #  'interesting',
    #  'kid answered',
    #  'kid is too old',
    #  'kid is too young',
    #  'kid too old',
    #  'kid too young',
    #  'no',
    #  'nope',
    #  'not sure',
    #  'not yet',
    #  'of course',
    #  'personal',
    #  'philosophical',
    #  'probably',
    #  'somewhat',
    #  'yes'}


import pandas as pd
from google.cloud import bigquery

In [3]:
#instantiate client
project = 'socos-quickstep-601'
client = bigquery.Client(project=project)

join_query="""
#standardSQL
SELECT a.JiveLearner.id as learner, \
b.message.jive_id as question, \
a.answer, a.last_modified, \
a.JiveEnvelope.name, \
b.message.learner_name, \
a.tags.tag, \
a.tags.metatag, \
c.who, \
c.text, \
c.answer_type, ARRAY_TO_STRING(a.tags.tag, ', ') as answer_tag, ARRAY_TO_STRING(a.tags.metatag, ', ') as metatags
FROM `socos-quickstep-601.museathome.BinaryQuestionAnswer` as a
JOIN `socos-quickstep-601.museathome.JiveEnvelope` as b ON a.JiveEnvelope.name=b.__key__.name
JOIN `socos-quickstep-601.museathome.questions` as c ON CAST(b.message.jive_id AS NUMERIC) = c.id
ORDER BY a.JiveLearner.id, b.message.learner_name, question ASC
"""

job_config = bigquery.QueryJobConfig()
join_query_job = client.query(join_query, location = 'US')
res = join_query_job.result()

#create dataframes
combined_df = res.to_dataframe()
combined_true = combined_df[combined_df['answer'] == True]
combined_false = combined_df[combined_df['answer'] == False]

#only select the last modified from all of the keys with the same name
combined_df = combined_df.sort_values('last_modified').drop_duplicates(subset='name',keep='last')

#rows of final df
learner_df = combined_df[['learner']]
learner_df.reset_index(inplace=True, drop=True)
learner_df = learner_df.drop_duplicates(keep='last')
learner_df = learner_df.set_index('learner')

#there are fewer questions answered
#than there are questions in the question database
#so we are going to query the questions directly from the questions database

questions_query="""
#standardSQL
SELECT * FROM `socos-quickstep-601.museathome.questions`
"""
job_config = bigquery.QueryJobConfig()
questions_query_job = client.query(questions_query, location = 'US')
res = questions_query_job.result()
questions_df = res.to_dataframe()

questions_df = questions_df[['id']].drop_duplicates(keep='last')
questions_df = questions_df.reset_index(drop=True)

#create muse_model_df
dummy = pd.get_dummies(questions_df['id'])
muse_model_df = pd.concat([learner_df, dummy])

#only selects all the Musers
muse_model_df = muse_model_df[:2967]

In [4]:
print('The length of the join query is: ' + str(combined_df.shape[0]))

The length of the join query is: 34355

In [21]:
def process_true(df, muse_model_df):
    #True answers
    for i in df.index:
        learner = df.at[i, 'learner']
        question = df.at[i, 'question']
        question = int(question)
        muse_model_df.loc[learner, question] = 1

def process_false(df, muse_model_df):        
    #False answers
    for i in df.index:
        learner = df.at[i, 'learner']
        question = df.at[i, 'question']
        question = int(question)
        muse_model_df.loc[learner, question] = -1

In [6]:
#create new 'final_answer' column of only the answers
for i in combined_df.index:
    if 'answer' in combined_df.at[i, 'metatag']:
        combined_df.at[i, 'final_answer'] = combined_df.at[i, 'tag'][0]

In [20]:
combined_df['final_answer'].value_counts().sum()

15563

In [8]:
# Get only answers that don't have True/False answers and are not null in the tags
combined_tags_final = combined_df[combined_df.final_answer.notnull() & combined_df.answer.isnull()]

In [42]:
# Dictionary for numbers
def switcher(ans):
    answers = {
        'yes': 1,
        'no': -1,
        'definitely': 2,
        'probably': 1,
        'somewhat': 0,
        'barely': -1,
        'nope': -2
    }
    
    return answers.get(ans, None)

In [43]:
def add_tags(df, muse_model_df):
    for i in df.index:    
        answer = df.at[i, 'final_answer'].lower()
        learner = df.at[i, 'learner']
        question = df.at[i, 'question']
        question = int(question) 
        
        muse_answer = switcher(answer)
        muse_model_df.loc[learner, question] = muse_answer
        
        return

In [48]:
switcher('definitely')

2

In [22]:
process_true(combined_true, muse_model_df)
process_false(combined_false, muse_model_df)

In [44]:
add_tags(combined_tags_final, muse_model_df)

In [45]:
muse_model_df.count().sum()

21610

In [56]:
21610 + 9451

31061

In [46]:
muse_model_df[367].value_counts()

 1.0    27
-1.0     2
Name: 367, dtype: int64

In [78]:
# Dictionary for numbers
answers = {
        'yes': 1,
        'no': -1,
        'definitely': 2,
        'probably': 1,
        'somewhat': 0,
        'barely': -1,
        'nope': -2
        'true': 1,
        'false': -1
    }

lst_not_caught = []

for i in combined_tags_final.index:    
    answer = combined_tags_final.at[i, 'final_answer'].lower()
    learner = combined_tags_final.at[i, 'learner']
    question = combined_tags_final.at[i, 'question']
    question = int(question) 
        
    muse_answer = answers.get(answer, None)
    muse_model_df.loc[learner, question] = muse_answer
    
    tup = (learner, question, answer, muse_answer)
    
    #if tup[2] is None:
    lst_not_caught.append(tup)

In [79]:
lst_not_caught

[(5751903552012288, 13, 'yes', 1),
 (5735286357098496, 661, 'yes', 1),
 (5685665089978368, 845, 'yes', 1),
 (5767494685949952, 16, 'barely', -1),
 (5767494685949952, 21, 'yes', 1),
 (5649952705347584, 22, 'yes', 1),
 (5767494685949952, 485, 'no', -1),
 (6231905506689024, 927, 'yes', 1),
 (5685665089978368, 845, 'yes', 1),
 (5751903552012288, 682, 'yes', 1),
 (5767494685949952, 378, 'yes', 1),
 (5665497936822272, 578, 'probably', 1),
 (5638203017003008, 837, 'yes', 1),
 (5735286357098496, 875, 'yes', 1),
 (5665497936822272, 890, 'yes', 1),
 (5741642204053504, 184, 'nope', -2),
 (5665497936822272, 930, 'probably', 1),
 (5665497936822272, 806, 'yes', 1),
 (5665497936822272, 579, 'definitely', 2),
 (5649952705347584, 595, 'barely', -1),
 (5767494685949952, 627, 'probably', 1),
 (5638203017003008, 822, 'no', -1),
 (5767494685949952, 391, 'probably', 1),
 (5751903552012288, 269, 'yes', 1),
 (5751903552012288, 797, 'yes', 1),
 (5701810610241536, 851, 'not sure', None),
 (5649952705347584, 563, 'yes', 1),
 (5767494685949952, 741, 'no', -1),
 (5767494685949952, 489, 'no', -1),
 (5767494685949952, 11, 'somewhat', 0),
 (5751903552012288, 618, 'yes', 1),
 (5767494685949952, 590, 'definitely', 2),
 (5638203017003008, 161, 'not sure', None),
 (5741642204053504, 928, 'nope', -2),
 (5751903552012288, 691, 'yes', 1),
 (5767494685949952, 701, 'somewhat', 0),
 (5638203017003008, 677, 'probably', 1),
 (5741642204053504, 788, 'barely', -1),
 (5685665089978368, 845, 'yes', 1),
 (5649952705347584, 546, 'barely', -1),
 (5649952705347584, 563, 'definitely', 2),
 (5767494685949952, 739, 'somewhat', 0),
 (5665497936822272, 837, 'probably', 1),
 (5665497936822272, 575, 'yes', 1),
 (5767494685949952, 383, 'yes', 1),
 (5735286357098496, 863, 'yes', 1),
 (5735286357098496, 790, 'no', -1),
 (5638203017003008, 885, 'yes', 1),
 (5685665089978368, 677, 'yes', 1),
 (5735286357098496, 668, "doesn't apply", None),
 (5665497936822272, 748, 'yes', 1),
 (5638203017003008, 558, 'no', -1),
 (5751903552012288, 15, 'yes', 1),
 (5685665089978368, 778, 'somewhat', 0),
 (5735286357098496, 120, 'not sure', None),
 (5638203017003008, 885, 'no', -1),
 (5685665089978368, 677, 'yes', 1),
 (5723012934402048, 369, 'definitely', 2),
 (5767494685949952, 617, 'probably', 1),
 (5649952705347584, 703, 'yes', 1),
 (5665497936822272, 158, 'definitely', 2),
 (5638203017003008, 845, 'somewhat', 0),
 (5767494685949952, 711, 'somewhat', 0),
 (5767494685949952, 843, 'yes', 1),
 (5649952705347584, 577, 'yes', 1),
 (5649952705347584, 577, 'yes', 1),
 (5767494685949952, 804, 'barely', -1),
 (5767494685949952, 474, 'probably', 1),
 (5649952705347584, 862, 'somewhat', 0),
 (5767494685949952, 682, 'yes', 1),
 (5638203017003008, 372, 'yes', 1),
 (6231905506689024, 159, 'no', -1),
 (5638203017003008, 884, 'yes', 1),
 (5767494685949952, 864, 'yes', 1),
 (5767494685949952, 577, 'definitely', 2),
 (5685665089978368, 677, 'yes', 1),
 (5665497936822272, 669, 'no', -1),
 (5767494685949952, 700, 'probably', 1),
 (5751903552012288, 399, 'yes', 1),
 (5685665089978368, 194, 'no', -1),
 (5767494685949952, 646, 'no', -1),
 (5767494685949952, 810, 'yes', 1),
 (6231905506689024, 159, 'yes', 1),
 (5638203017003008, 590, 'yes', 1),
 (5767494685949952, 684, 'no', -1),
 (5767494685949952, 403, 'yes', 1),
 (5638203017003008, 848, 'yes', 1),
 (5649952705347584, 307, 'somewhat', 0),
 (5767494685949952, 735, 'probably', 1),
 (5735286357098496, 699, 'definitely', 2),
 (5751903552012288, 261, 'yes', 1),
 (5685665089978368, 677, 'yes', 1),
 (5767494685949952, 840, 'barely', -1),
 (5723012934402048, 368, 'barely', -1),
 (5767494685949952, 8, 'no', -1),
 (5665497936822272, 716, 'yes', 1),
 (5649952705347584, 41, 'no', -1),
 (5767494685949952, 577, 'definitely', 2),
 (5751903552012288, 503, 'no', -1),
 (5649952705347584, 526, 'yes', 1),
 (5649952705347584, 17, 'yes', 1),
 (5767494685949952, 378, 'yes', 1),
 (5767494685949952, 17, 'yes', 1),
 (5665497936822272, 587, 'somewhat', 0),
 (5665497936822272, 156, 'yes', 1),
 (5746392672763904, 844, 'probably', 1),
 (5649952705347584, 738, 'yes', 1),
 (5638203017003008, 677, 'probably', 1),
 (5767494685949952, 552, 'somewhat', 0),
 (5638203017003008, 922, 'yes', 1),
 (5638203017003008, 211, 'definitely', 2),
 (5638203017003008, 685, 'nope', -2),
 (5638203017003008, 689, 'yes', 1),
 (5735286357098496, 788, 'definitely', 2),
 (5735286357098496, 390, 'yes', 1),
 (5665497936822272, 606, 'yes', 1),
 (5751903552012288, 720, 'yes', 1),
 (5767494685949952, 385, 'no', -1),
 (5649952705347584, 881, 'definitely', 2),
 (5767494685949952, 650, 'yes', 1),
 (5767494685949952, 818, 'definitely', 2),
 (5767494685949952, 418, 'yes', 1),
 (5685665089978368, 845, 'definitely', 2),
 (5685665089978368, 800, 'yes', 1),
 (5638203017003008, 932, 'yes', 1),
 (5751903552012288, 818, 'yes', 1),
 (5685665089978368, 845, 'yes', 1),
 (5751903552012288, 374, 'no', -1),
 (5767494685949952, 76, 'somewhat', 0),
 (5649952705347584, 809, 'yes', 1),
 (5701810610241536, 581, 'yes', 1),
 (5638203017003008, 879, 'interesting', None),
 (5735286357098496, 780, 'definitely', 2),
 (5685665089978368, 845, 'definitely', 2),
 (5685665089978368, 598, 'yes', 1),
 (5649952705347584, 577, 'definitely', 2),
 (5638203017003008, 421, 'definitely', 2),
 (5767494685949952, 409, 'yes', 1),
 (5665497936822272, 563, 'definitely', 2),
 (5767494685949952, 830, 'somewhat', 0),
 (5685665089978368, 879, 'yes', 1),
 (5735286357098496, 855, 'somewhat', 0),
 (5751903552012288, 251, 'yes', 1),
 (5665497936822272, 796, 'definitely', 2),
 (5665497936822272, 80, 'definitely', 2),
 (5767494685949952, 684, 'somewhat', 0),
 (5638203017003008, 699, 'somewhat', 0),
 (5767494685949952, 25, 'definitely', 2),
 (5767494685949952, 471, 'yes', 1),
 (5665497936822272, 809, 'no', -1),
 (5665497936822272, 887, 'no', -1),
 (5751903552012288, 798, 'yes', 1),
 (5665497936822272, 887, 'no', -1),
 (5665497936822272, 598, 'yes', 1),
 (5735286357098496, 24, 'yes', 1),
 (5665497936822272, 748, 'yes', 1),
 (5751903552012288, 405, 'yes', 1),
 (5751903552012288, 255, 'yes', 1),
 (5751903552012288, 272, 'yes', 1),
 (5638203017003008, 845, 'kid too old', None),
 (5723012934402048, 371, 'yes', 1),
 (5751903552012288, 57, 'yes', 1),
 (5751903552012288, 81, 'yes', 1),
 (5665497936822272, 772, 'abstract', None),
 (5665497936822272, 156, 'kid answered', None),
 (5741642204053504, 677, 'no', -1),
 (5741642204053504, 199, 'no', -1),
 (5741642204053504, 778, 'yes', 1),
 (5741642204053504, 890, 'no', -1),
 (5741642204053504, 708, 'yes', 1),
 (5751903552012288, 264, 'yes', 1),
 (5751903552012288, 778, 'no', -1),
 (5751903552012288, 735, 'yes', 1),
 (5751903552012288, 603, 'no', -1),
 (5638203017003008, 272, 'yes', 1),
 (5638203017003008, 879, 'no', -1),
 (5638203017003008, 879, 'kid too young', None),
 (5638203017003008, 879, 'yes', 1),
 (5638203017003008, 879, 'no', -1),
 (5638203017003008, 845, 'no', -1),
 (5638203017003008, 845, 'no', -1),
 (5638203017003008, 845, 'yes', 1),
 (5638203017003008, 845, 'no', -1),
 (5767494685949952, 926, 'no', -1),
 (5638203017003008, 845, 'yes', 1),
 (5638203017003008, 909, 'yes', 1),
 (5638203017003008, 691, 'yes', 1),
 (5685665089978368, 870, 'good idea', None),
 (5638203017003008, 930, 'yes', 1),
 (5665497936822272, 685, 'yes', 1),
 (5665497936822272, 895, 'yes', 1),
 (5649952705347584, 39, 'yes', 1),
 (6231905506689024, 790, 'absolutely', None),
 (5685665089978368, 851, 'yes', 1),
 (5685665089978368, 404, 'yes', 1),
 (5665497936822272, 853, 'abstract', None),
 (5735286357098496, 5, 'yes', 1),
 (5665497936822272, 868, 'yes', 1),
 (5685665089978368, 9, 'yes', 1),
 (5685665089978368, 747, 'yes', 1),
 (5638203017003008, 371, 'yes', 1),
 (5638203017003008, 369, 'yes', 1),
 (5638203017003008, 368, 'yes', 1),
 (5638203017003008, 371, 'yes', 1),
 (5638203017003008, 369, 'yes', 1),
 (6231905506689024, 699, 'kid too old', None),
 (5665497936822272, 880, 'yes', 1),
 (5638203017003008, 368, 'yes', 1),
 (5665497936822272, 182, 'yes', 1),
 (5665497936822272, 667, 'yes', 1),
 (5665497936822272, 569, 'yes', 1),
 (5665497936822272, 856, 'no', -1),
 (5665497936822272, 575, 'yes', 1),
 (5665497936822272, 716, 'no', -1),
 (5665497936822272, 716, 'no', -1),
 (5665497936822272, 772, 'no', -1),
 (5638203017003008, 371, 'yes', 1),
 (6231905506689024, 14, 'yes', 1),
 (5638203017003008, 369, 'yes', 1),
 (5665497936822272, 5, 'yes', 1),
 (5638203017003008, 368, 'yes', 1),
 (5638203017003008, 371, 'yes', 1),
 (5638203017003008, 369, 'yes', 1),
 (5638203017003008, 368, 'yes', 1),
 (5638203017003008, 371, 'yes', 1),
 (5638203017003008, 369, 'yes', 1),
 (5638203017003008, 368, 'yes', 1),
 (5638203017003008, 368, 'yes', 1),
 (5638203017003008, 371, 'yes', 1),
 (5665497936822272, 25, 'yes', 1),
 (5665497936822272, 777, 'yes', 1),
 (5665497936822272, 178, 'yes', 1),
 (5665497936822272, 778, 'no', -1),
 (5665497936822272, 189, 'yes', 1),
 (5665497936822272, 770, 'no', -1),
 (5665497936822272, 713, 'yes', 1),
 (5665497936822272, 582, 'yes', 1),
 (5665497936822272, 815, 'no', -1),
 (5665497936822272, 659, 'yes', 1),
 (5665497936822272, 601, 'yes', 1),
 (5665497936822272, 851, 'yes', 1),
 (5665497936822272, 187, 'yes', 1),
 (5665497936822272, 682, 'yes', 1),
 (5665497936822272, 80, 'yes', 1),
 (5665497936822272, 610, 'no', -1),
 (5735286357098496, 13, 'yes', 1),
 (5657219571908608, 371, 'yes', 1),
 (6262400311361536, 13, 'yes', 1),
 (5631037082173440, 371, 'yes', 1),
 (5631037082173440, 368, 'yes', 1),
 (5239500347277312, 40, 'yes', 1),
 (5695127876009984, 18, 'no', -1),
 (5761885492215808, 14, 'yes', 1),
 (5706522961117184, 38, 'yes', 1),
 (5751903552012288, 590, 'yes', 1),
 (5140419025305600, 39, 'yes', 1),
 (5131256299782144, 24, 'yes', 1),
 (5738836835434496, 371, 'yes', 1),
 (5673596114436096, 367, 'yes', 1),
 (5359355520090112, 21, 'yes', 1),
 (5737682411978752, 698, 'no', -1),
 (6262400311361536, 741, 'yes', 1),
 (5697326781825024, 371, 'yes', 1),
 (5737682411978752, 797, 'no', -1),
 (5737682411978752, 182, 'yes', 1),
 (5737682411978752, 568, 'no', -1),
 (5136249954238464, 43, 'no', -1),
 (5738836835434496, 368, 'yes', 1),
 (5947893009612800, 42, 'no', -1),
 (5673490367643648, 926, 'no', -1),
 (5673490367643648, 15, 'no', -1),
 (5751903552012288, 847, 'yes', 1),
 (5749215942672384, 58, 'yes', 1),
 (5765283616653312, 24, 'yes', 1),
 (5733848012816384, 403, 'yes', 1),
 (5673490367643648, 5, 'yes', 1),
 (5462642772672512, 926, 'no', -1),
 (5768584097693696, 42, 'no', -1),
 (5695127876009984, 15, 'yes', 1),
 (5989180261793792, 13, 'yes', 1),
 (5727262821318656, 43, 'no', -1),
 (5656206764933120, 371, 'yes', 1),
 (5656206764933120, 367, 'yes', 1),
 (5206086944555008, 371, 'yes', 1),
 (5206086944555008, 367, 'yes', 1),
 (5759073916026880, 371, 'yes', 1),
 (5759073916026880, 368, 'yes', 1),
 (5705491514654720, 22, 'yes', 1),
 (5672338662096896, 371, 'no', -1),
 (5672338662096896, 367, 'yes', 1),
 (5720950444130304, 371, 'no', -1),
 (5720950444130304, 367, 'yes', 1),
 (5749298570461184, 371, 'no', -1),
 (5749298570461184, 367, 'yes', 1),
 (5635448399462400, 554, 'yes', 1),
 (5643814291111936, 15, 'yes', 1),
 (5643814291111936, 38, 'yes', 1),
 (5657219571908608, 368, 'yes', 1),
 (5716507619229696, 39, 'yes', 1),
 (5716507619229696, 590, 'yes', 1),
 (5082384487677952, 43, 'no', -1),
 (5732665235865600, 368, 'yes', 1),
 (5658902930653184, 371, 'yes', 1),
 (5658902930653184, 368, 'yes', 1),
 (5696172878462976, 35, 'yes', 1),
 (5239500347277312, 21, 'yes', 1),
 (5670048941211648, 371, 'yes', 1),
 (5670048941211648, 369, 'yes', 1),
 (5670048941211648, 368, 'yes', 1),
 (5670048941211648, 42, 'no', -1),
 (5206086944555008, 741, 'yes', 1),
 (5162582650388480, 40, 'no', -1),
 (5162582650388480, 4, 'no', -1),
 (5746784991182848, 1066, 'yes', 1),
 (5746784991182848, 42, 'no', -1),
 (4815924045545472, 43, 'no', -1),
 (5107098987790336, 590, 'yes', 1),
 (5694411304337408, 371, 'yes', 1),
 (5694411304337408, 368, 'yes', 1),
 (5739939803168768, 39, 'yes', 1),
 (5663804612411392, 42, 'no', -1),
 (5746784991182848, 13, 'yes', 1),
 (5746784991182848, 58, 'yes', 1),
 (5695308147195904, 371, 'yes', 1),
 (5695308147195904, 367, 'yes', 1),
 (5765283616653312, 4, 'yes', 1),
 (5205634144272384, 539, 'yes', 1),
 (5736495272951808, 371, 'no', -1),
 (5736495272951808, 367, 'yes', 1),
 (5725901165690880, 58, 'yes', 1),
 (5736495272951808, 58, 'yes', 1),
 (4929646726479872, 792, 'no', -1),
 (5271646650761216, 39, 'yes', 1),
 (5650472497053696, 590, 'yes', 1),
 (5767494685949952, 847, 'yes', 1),
 (5667627737284608, 590, 'yes', 1),
 (4929646726479872, 177, 'yes', 1),
 (5706522961117184, 5, 'yes', 1),
 (5128608989315072, 1059, 'no', -1),
 (5744039651442688, 371, 'yes', 1),
 (5744039651442688, 368, 'yes', 1),
 (4929646726479872, 708, 'no', -1),
 (4929646726479872, 195, 'yes', 1),
 (5748286602346496, 25, 'yes', 1),
 (5677552651730944, 15, 'no', -1),
 (5677552651730944, 18, 'no', -1),
 (5752930401517568, 15, 'no', -1),
 (5723548412805120, 847, 'yes', 1),
 (4929646726479872, 175, 'yes', 1),
 (5694411304337408, 58, 'yes', 1),
 (5513676127731712, 38, 'no', -1),
 (5732665235865600, 367, 'yes', 1),
 (5727790498316288, 38, 'yes', 1),
 (5989180261793792, 42, 'no', -1),
 (5206086944555008, 1059, 'yes', 1),
 (5759073916026880, 58, 'yes', 1),
 (5666691417636864, 18, 'no', -1),
 (4929646726479872, 52, 'yes', 1),
 (4929646726479872, 38, 'yes', 1),
 (5712967307886592, 371, 'yes', 1),
 (5712967307886592, 368, 'yes', 1),
 (5743640890572800, 371, 'yes', 1),
 (5743640890572800, 368, 'yes', 1),
 (5723548412805120, 38, 'yes', 1),
 (5140419025305600, 42, 'philosophical', None),
 (5633461826093056, 367, 'no', -1),
 (5767494685949952, 58, 'yes', 1),
 (5765290612752384, 371, 'no', -1),
 (5765290612752384, 368, 'yes', 1),
 (5633211778465792, 371, 'yes', 1),
 (5633211778465792, 367, 'yes', 1),
 (5691127080419328, 837, 'yes', 1),
 (5691127080419328, 569, 'yes', 1),
 (5691127080419328, 661, 'no', -1),
 (5691127080419328, 151, 'no', -1),
 (5691127080419328, 688, 'yes', 1),
 (5691127080419328, 700, 'no', -1),
 (5691127080419328, 803, 'no', -1),
 (5691127080419328, 618, 'no', -1),
 (5691127080419328, 26, 'yes', 1),
 (5691127080419328, 52, 'no', -1),
 (5691127080419328, 176, 'yes', 1),
 (5691127080419328, 5, 'yes', 1),
 (5694411304337408, 13, 'yes', 1),
 (5748286602346496, 847, 'yes', 1),
 (5026561858207744, 602, 'no', -1),
 (5026561858207744, 25, 'yes', 1),
 (5026561858207744, 593, 'no', -1),
 (5026561858207744, 375, 'no', -1),
 (5026561858207744, 21, 'yes', 1),
 (5026561858207744, 17, 'yes', 1),
 (5026561858207744, 553, 'no', -1),
 (5026561858207744, 509, 'no', -1),
 (5026561858207744, 53, 'no', -1),
 (5743640890572800, 43, 'no', -1),
 (5761390144913408, 43, 'no', -1),
 (4929646726479872, 42, 'no', -1),
 (5120614310346752, 38, 'yes', 1),
 (5120614310346752, 35, 'yes', 1),
 (5665497936822272, 43, 'no', -1),
 (5665497936822272, 43, 'no', -1),
 (5691127080419328, 25, 'yes', 1),
 (5743640890572800, 5, 'no', -1),
 (5131256299782144, 40, 'yes', 1),
 (5128608989315072, 25, 'yes', 1),
 (5738841684049920, 371, 'yes', 1),
 (5738841684049920, 367, 'yes', 1),
 (4815924045545472, 38, 'yes', 1),
 (4929646726479872, 39, 'yes', 1),
 (5639486859902976, 371, 'yes', 1),
 (5639486859902976, 368, 'yes', 1),
 (5026561858207744, 62, 'no', -1),
 (5643814291111936, 42, 'no', -1),
 (5736495272951808, 42, 'no', -1),
 (5685665089978368, 39, 'somewhat', 0),
 (5720785188552704, 1059, 'no', -1),
 (5650660334764032, 4, 'yes', 1),
 (5639486859902976, 18, 'no', -1),
 (5656462332264448, 5, 'yes', 1),
 (6453765800460288, 5, 'definitely', 2),
 (5738841684049920, 40, 'yes', 1),
 (4800470300229632, 368, 'yes', 1),
 (4800470300229632, 371, 'yes', 1),
 (6043597312884736, 368, 'yes', 1),
 (6043597312884736, 371, 'yes', 1),
 (5683762654347264, 58, 'no', -1),
 (5993028099506176, 367, 'yes', 1),
 (5993028099506176, 371, 'yes', 1),
 (6224435568705536, 368, 'yes', 1),
 (6224435568705536, 371, 'yes', 1),
 (5743640890572800, 40, 'no', -1),
 (5989180261793792, 41, 'nope', -2),
 (5725901165690880, 15, 'nope', -2),
 (5743640890572800, 39, 'yes', 1),
 (5271646650761216, 5, 'yes', 1),
 (5767494685949952, 43, 'no', -1),
 (5725901165690880, 22, 'definitely', 2),
 (5667627737284608, 5, 'nope', -2),
 (5140419025305600, 5, 'yes', 1),
 (5736495272951808, 13, 'yes', 1),
 (5143752456798208, 38, 'definitely', 2),
 (5143752456798208, 590, 'definitely', 2),
 (5765283616653312, 25, 'definitely', 2),
 (5665731089793024, 24, 'somewhat', 0),
 (5665731089793024, 43, 'nope', -2),
 (5665731089793024, 25, 'definitely', 2),
 (5728489521020928, 371, 'no', -1),
 (6224435568705536, 38, 'yes', 1),
 (5731988359086080, 4, 'definitely', 2),
 (5731988359086080, 5, 'somewhat', 0),
 (5656462332264448, 1059, 'nope', -2),
 (5725996342837248, 58, 'nope', -2),
 (5725996342837248, 13, 'definitely', 2),
 (5725996342837248, 43, 'nope', -2),
 (5694411304337408, 39, 'definitely', 2),
 (5712967307886592, 24, 'yes', 1),
 (5728489521020928, 367, 'yes', 1),
 (6057041550376960, 40, 'definitely', 2),
 (5635448399462400, 13, 'definitely', 2),
 (5765290612752384, 18, 'nope', -2),
 (5741974376153088, 367, 'yes', 1),
 (5741974376153088, 371, 'yes', 1),
 (5687213006258176, 367, 'no', -1),
 (5740915398279168, 371, 'yes', 1),
 (5673615206907904, 368, 'yes', 1),
 (5673615206907904, 371, 'yes', 1),
 (5639486859902976, 22, 'yes', 1),
 (6043597312884736, 41, 'no', -1),
 (5665731089793024, 39, 'definitely', 2),
 (5649952705347584, 35, 'definitely', 2),
 (5989180261793792, 38, 'yes', 1),
 (5643814291111936, 1066, 'yes', 1),
 (5727262821318656, 35, 'definitely', 2),
 (5720693702393856, 42, 'no', -1),
 (5720693702393856, 21, 'yes', 1),
 (5639486859902976, 43, 'nope', -2),
 (5731988359086080, 24, 'definitely', 2),
 (5737701907103744, 22, 'yes', 1),
 (5658145321910272, 4, 'yes', 1),
 (5725901165690880, 41, 'no', -1),
 (5762578928107520, 42, 'no', -1),
 (5656462332264448, 4, 'definitely', 2),
 (5655148575588352, 41, 'nope', -2),
 (5658145321910272, 40, 'no', -1),
 (5658145321910272, 42, 'nope', -2),
 (5673615206907904, 18, 'no', -1),
 (5765283616653312, 847, 'somewhat', 0),
 (5702821588500480, 368, 'yes', 1),
 (5702821588500480, 371, 'yes', 1),
 (5139871635079168, 368, 'yes', 1),
 (5139871635079168, 371, 'yes', 1),
 (5683762654347264, 1066, 'no', -1),
 (5734409529458688, 368, 'not yet', None),
 (5502573435944960, 367, 'yes', 1),
 (5502573435944960, 371, 'yes', 1),
 (5126704741744640, 367, 'yes', 1),
 (5126704741744640, 371, 'yes', 1),
 (5762578928107520, 1097, 'no', -1),
 (5181771993841664, 368, 'yes', 1),
 (5181771993841664, 371, 'yes', 1),
 (5668628145897472, 368, 'yes', 1),
 (5707729528160256, 367, 'yes', 1),
 (5707729528160256, 371, 'yes', 1),
 (5688531158564864, 367, 'yes', 1),
 (5688531158564864, 371, 'yes', 1),
 (5755020741967872, 367, 'yes', 1),
 (5755020741967872, 371, 'yes', 1),
 (5157879359209472, 367, 'no', -1),
 (5157879359209472, 368, 'yes', 1),
 (6000129291059200, 367, 'yes', 1),
 (6000129291059200, 371, 'yes', 1),
 (4845229765033984, 371, 'no', -1),
 (5971129671876608, 368, 'no', -1),
 (5971129671876608, 371, 'no', -1),
 (5718908656943104, 368, 'no', -1),
 (5718908656943104, 371, 'yes', 1),
 (5155704360927232, 368, 'nope', -2),
 (5155704360927232, 371, 'definitely', 2),
 (5717649963089920, 371, 'no', -1),
 (5717649963089920, 38, 'yes', 1),
 (5089588305461248, 367, 'yes', 1),
 (6277138575523840, 367, 'yes', 1),
 (6277138575523840, 371, 'yes', 1),
 (5678446575353856, 367, 'yes', 1),
 (5665731089793024, 58, 'yes', 1),
 (5663946765762560, 368, 'no', -1),
 (5663946765762560, 371, 'yes', 1),
 (5744279834066944, 368, 'yes', 1),
 (5744279834066944, 371, 'yes', 1),
 (5683762654347264, 847, 'yes', 1),
 (5661745997676544, 371, 'yes', 1),
 (5655148575588352, 847, 'yes', 1),
 (5126704741744640, 58, 'yes', 1),
 (5695143898251264, 24, 'yes', 1),
 (5652538258882560, 368, 'definitely', 2),
 (5652538258882560, 371, 'definitely', 2),
 (5155704360927232, 24, 'yes', 1),
 (5112343444848640, 371, 'yes', 1),
 (5794748652584960, 368, 'kid too young', None),
 (5794748652584960, 371, 'no', -1),
 (5666691417636864, 39, 'yes', 1),

In [77]:
len(lst_not_caught)

9451

In [97]:
len(set(lst_not_caught)) #There are 250 duplicates

9203

In [80]:
lst_not_caught[0][3]

1

In [86]:
cnt = 0
for word in lst_not_caught:
    if word[3] == None:
        print(word)
        cnt += 1
        
print(cnt)

(5701810610241536, 851, 'not sure', None)
(5638203017003008, 161, 'not sure', None)
(5735286357098496, 668, "doesn't apply", None)
(5735286357098496, 120, 'not sure', None)
(5638203017003008, 879, 'interesting', None)
(5638203017003008, 845, 'kid too old', None)
(5665497936822272, 772, 'abstract', None)
(5665497936822272, 156, 'kid answered', None)
(5638203017003008, 879, 'kid too young', None)
(5685665089978368, 870, 'good idea', None)
(6231905506689024, 790, 'absolutely', None)
(5665497936822272, 853, 'abstract', None)
(6231905506689024, 699, 'kid too old', None)
(5140419025305600, 42, 'philosophical', None)
(5734409529458688, 368, 'not yet', None)
(5794748652584960, 368, 'kid too young', None)
(4785802315825152, 367, 'kid too young', None)
(5764122046103552, 367, 'kid too young', None)
(5124005757452288, 367, 'kid too young', None)
(5640610329395200, 371, 'not yet', None)
(5677937890164736, 368, 'kid too young', None)
(5726056312995840, 368, 'kid too young', None)
(5625541864456192, 371, 'kid too young', None)
(5625541864456192, 368, 'kid too young', None)
(5720785188552704, 22, 'absolutely', None)
(5088376881414144, 368, 'not yet', None)
(5745074562400256, 368, 'kid too young', None)
(5203033449299968, 5, 'absolutely', None)
(4640195836116992, 368, 'kid too young', None)
(6231905506689024, 772, 'personal', None)
(6268823116185600, 1097, 'kid too young', None)
(6179571170803712, 1097, 'kid too young', None)
(5710207212584960, 368, 'absolutely', None)
(4640195836116992, 1097, 'not yet', None)
(5726056312995840, 5, 'not yet', None)
(5737414555336704, 368, 'kid too young', None)
(5735733880946688, 368, 'kid too young', None)
(5735733880946688, 371, 'not yet', None)
(5121247104991232, 368, 'absolutely', None)
(4742349653540864, 368, 'of course', None)
(4742349653540864, 371, 'not yet', None)
(5742800276553728, 368, 'kid too young', None)
(5644222858264576, 367, 'kid too young', None)
(5452546655125504, 368, 'not yet', None)
(6245154952314880, 368, 'not yet', None)
(6266045270589440, 371, 'personal', None)
(5641868075335680, 368, 'of course', None)
(5641868075335680, 367, 'of course', None)
(6329334969139200, 367, 'of course', None)
(6279186192793600, 371, 'of course', None)
(5673440514146304, 368, 'kid too young', None)
(5695143898251264, 25, 'absolutely', None)
(5717358014365696, 371, "doesn't apply", None)
(5732218685095936, 18, "doesn't apply", None)
(5688119084974080, 368, 'good idea', None)
(5629932830982144, 368, 'not yet', None)
(5685717191622656, 1097, 'kid too young', None)
(6266045270589440, 24, 'of course', None)
(5755801964642304, 368, 'good idea', None)
(5717649963089920, 22, 'absolutely', None)
(5651417146589184, 847, 'absolutely', None)
(5443702461825024, 367, 'kid too young', None)
(5739921067212800, 367, 'not yet', None)
(5111126970859520, 5, 'of course', None)
(5757135430352896, 371, 'not yet', None)
(5743208831123456, 368, 'not yet', None)
(5736210450350080, 368, 'abstract', None)
(5635473066164224, 368, "doesn't apply", None)
(5759785949462528, 371, 'not yet', None)
(6325161598910464, 741, 'kid answered', None)
(5722688953778176, 367, 'kid too young', None)
(5634249336029184, 368, 'kid too young', None)
(5090268520906752, 926, "doesn't apply", None)
(5719284705656832, 367, 'absolutely', None)
(5743033593102336, 15, "doesn't apply", None)
(6289502549049344, 367, 'kid too young', None)
(5670738522537984, 368, 'absolutely', None)
(5125102253375488, 371, 'personal', None)
(5643598557085696, 367, 'kid too young', None)
(5649952705347584, 730, 'kid answered', None)
(5767494685949952, 790, 'abstract', None)
(5141049768935424, 39, 'not yet', None)
(5766425318785024, 371, 'of course', None)
(5169934128644096, 368, 'absolutely', None)
(5722177131249664, 367, 'of course', None)
(5632436297793536, 1099, 'absolutely', None)
(5696172878462976, 741, 'interesting', None)
(5750604739641344, 368, 'absolutely', None)
(4649037902905344, 368, 'kid too young', None)
(5707542458007552, 371, "doesn't apply", None)
(5727159620468736, 367, 'of course', None)
(5697517501022208, 371, 'not yet', None)
(5697517501022208, 368, 'not yet', None)
(4799663949479936, 368, 'of course', None)
(4767841362378752, 368, 'of course', None)
(4898910074044416, 367, 'of course', None)
(5862932126629888, 368, "doesn't apply", None)
(4643024344711168, 368, 'kid too young', None)
(5660707886465024, 371, 'of course', None)
(6028127675351040, 371, "doesn't apply", None)
(5634033488756736, 368, 'absolutely', None)
(6274286780153856, 371, 'not yet', None)
(5132360504836096, 367, 'kid too young', None)
(6555171702177792, 38, 'absolutely', None)
(6041811776700416, 368, 'absolutely', None)
(6255506901434368, 1099, 'absolutely', None)
(5651996518383616, 367, 'kid too young', None)
(4671325159292928, 847, 'of course', None)
(5658329145671680, 371, 'not yet', None)
(5658329145671680, 368, 'kid too young', None)
(5649748371439616, 371, 'of course', None)
(5649748371439616, 368, 'kid too young', None)
(5762316612141056, 371, 'kid too young', None)
(5762316612141056, 368, 'kid too young', None)
(6299988065779712, 368, 'absolutely', None)
(5671522379235328, 1099, "doesn't apply", None)
(5699817531506688, 371, 'kid too old', None)
(6555171702177792, 42, 'philosophical', None)
(5638477186072576, 13, 'interesting', None)
(5758805996470272, 368, 'kid too young', None)
(5644111176531968, 13, 'good idea', None)
121

In [51]:
muse_model_df.count().sum()

30321

In [54]:
combined_tags_final['final_answer'].value_counts().sum()

9451

In [55]:
combined_tags_final['final_answer'].value_counts()

yes              5155
definitely       1953
no               1180
nope              698
somewhat          141
probably           96
barely             64
Yes                34
kid too young      33
not yet            19
absolutely         18
of course          16
No                  9
doesn't apply       9
good idea           4
abstract            4
kid answered        3
Not sure            3
kid too old         3
personal            3
interesting         3
philosophical       2
Doesn't apply       1
Name: final_answer, dtype: int64

In [13]:
#total number of answers without answer tags is 468
#total number of answers not in muse_model from combined_df is 1067

In [14]:
34355 - 33288

1067

In [15]:
1067 - 468

599

In [16]:
# Must add letter in front of columns to upload to Big Query
new_cols = list(muse_model_df.columns)

for i in range(len(new_cols)):
    word = str(new_cols[i])
    new_cols[i] = 'q' + word

In [19]:
muse_model_df.count().sum()

21610

In [59]:
# for i in combined_df.index:
#     
(learner, question) =  (1,2)

In [63]:
tup = (learner, question, 4)

In [66]:
tup[0]

1

In [65]:
tup

(1, 2, 4)

In [58]:
combined_df['question'].value_counts()

371     2090
367     1433
368     1346
24       409
18       404
25       397
13       396
41       380
15       376
40       369
590      368
22       362
847      314
4        304
39       285
5        277
38       274
43       273
42       268
58       257
2        255
10       234
1097     209
1099     200
390      122
8        121
106      117
14       116
57       115
26       114
        ...
109        3
442        3
463        3
147        3
139        2
112        2
439        2
150        2
149        2
129        2
218        2
446        2
145        1
215        1
197        1
196        1
148        1
128        1
874        1
206        1
191        1
933        1
935        1
324        1
198        1
339        1
326        1
138        1
441        1
931        1
Name: question, Length: 803, dtype: int64

In [40]:
combined_df.count()

learner          34355
question         34355
answer           24389
last_modified    34355
name             34355
learner_name     34355
tag              34355
metatag          34355
who              34355
text             34355
answer_type      34355
answer_tag       16031
metatags         16031
final_answer     15563
dtype: int64

In [41]:
24389 + 15563

39952

In [87]:
combined_df

,learner,question,answer,last_modified,name,learner_name,tag,metatag,who,text,answer_type,answer_tag,metatags,final_answer
37686,6298093637074944,40,True,2017-01-15 00:56:07.024890+00:00,nXJIar4lFgfgyXngcCoT434EdTwU2Vv4,Jack,[],[],parent,Do you have a graduate degree?,binary,None,None,NaN
2097,4999681536950272,152,True,2017-01-15 00:56:07.025080+00:00,cxKsk4j2ceAAj6WKpcsHDyXFgOmuKZs2,Rowan,[],[],child,Does {kid_name} cling to you or primary caregi...,scale,None,None,NaN
29958,5750743172644864,510,True,2017-01-15 00:56:07.025240+00:00,1hAPwIBJVEmwQLBVPXtxKy1qB6tTMwCA,Brady,[],[],child,Does {kid_name} anticipate likely outcomes of ...,scale,None,None,NaN
19756,5689015533568000,200,True,2017-01-15 00:56:07.025390+00:00,RjL7yAT8LV381Rr6nxlXiPkoZ8p76gtm,Alchemy,[yes],[answer],child,Does {kid_name} have temper tantrums?,scale,yes,answer,yes
3077,5078095828615168,16,False,2017-01-15 00:56:07.025750+00:00,4ZZO7qdG1DOuSspZeaR3NVmyc7tGPlL6,Tank,[],[],parent,Do you have a hard time maintaining focus if a...,scale,None,None,NaN
34657,5947893009612800,686,True,2017-01-15 00:56:07.025930+00:00,fQtzzIhJIwaGPCoxPklyfEE8jNS6yR0T,Margo,[yes],[answer],parent,"In the last week, have you spent time playing ...",scale,yes,answer,yes
1761,4920672459423744,891,False,2017-01-15 00:56:07.026480+00:00,01C3KSV4fkBSdjoelJSc3LgQUuVxGicK,Sam,[no],[answer],parent,Let’s assume a tax accountant and an artist ma...,scale,no,answer,no
17035,5673490367643648,773,True,2017-01-15 00:56:07.027430+00:00,dHDKkxi9v9TO7fK9y9XsLDd7pq9694JS,Oliver,[yes],[answer],child,"In the past week, has {kid_name} lost {their} ...",scale,yes,answer,yes
38806,6496032036749312,821,True,2017-01-15 00:56:07.027690+00:00,AIezB9OSCjUnQ25cKtEACa8UBUskbfC7,Grayson,[],[],child,Do you and {kid_name} talk about things {kid_n...,scale,None,None,NaN
20345,5690996151025664,213,True,2017-01-15 00:56:07.027920+00:00,UofeP3xFcLVFp1zyZu19puM6o2BYXgbY,Lucas,[],[],child,Will {kid_name} scribble to draw?,scale,None,None,NaN
23536,5714347888214016,486,True,2017-01-15 00:56:07.028130+00:00,mpj4BoG6sTGiGZVf3MFxMrx4s7zTzHWF,Ben,[],[],parent,"In the last year, has work distracted you from...",scale,None,None,NaN
33228,5767494685949952,495,False,2017-01-15 00:56:07.028330+00:00,JFxddVDpIsKoyEmeo4inimHsDTu9WBqA,Thumper,[],[],child,Does {kid_name} consider how {their} actions m...,scale,None,None,NaN
37210,6262400311361536,910,False,2017-01-15 00:56:07.028540+00:00,ZczF3naYdFXbpkOSkUubuxc34QoRQYQi,James,[],[],child,It’s a lazy weekend and you just realized you ...,scale,None,None,NaN
30027,5750885544099840,565,True,2017-01-15 00:56:07.028740+00:00,koDi56amrHvAtcA7tzEPnl9xMRD5l632,Henry,[],[],parent,Do you enjoy reading with or to {kid_name}?,scale,None,None,NaN
24743,5721365428568064,848,True,2017-01-15 00:56:07.028990+00:00,7jGA8bIEHiZNZK9hV66MCsiyb3DC7P2J,Sam,[],[],parent,If {kid_name} stopped doing something {they} e...,scale,None,None,NaN
36749,6244390976618496,610,True,2017-01-15 00:56:07.029210+00:00,MduYr8OOxk5meVatpotbeDAWRBNPqvqJ,Archie,[],[],child,Does {kid_name} have a hard time adjusting to ...,scale,None,None,NaN
9609,5629805013762048,415,True,2017-01-15 00:56:07.029450+00:00,bBs9pJh9hgAoUww02TGw8HwEpG9GXgWK,Noki,[],[],child,Does {kid_name} engage in learning activities ...,scale,None,None,NaN
8647,5375900807856128,831,True,2017-01-15 00:56:07.029600+00:00,WFXDb94xq9DOiTIX5ZSHJubnrVgWgANj,Cameron,[],[],parent,Do you notice you have a tendency to be impati...,scale,None,None,NaN
37855,6298431597314048,603,False,2017-01-15 00:56:07.029730+00:00,zu39PY6iMMaqJ7zK9Bqto6gTx8fuNALf,Mia,[],[],parent,Do you believe that money is actually the secr...,scale,None,None,NaN
18155,5682510201618432,193,True,2017-01-15 00:56:07.029860+00:00,2OH1oFt4jrcdhCLVcUdZRLtCb8BdmDjP,Zohan,[],[],child,Will {kid_name} bang 2 objects together?,scale,None,None,NaN
35698,6057041550376960,372,True,2017-01-15 00:56:07.029990+00:00,0QTzFlztLZw9d7U0fxfKqL4pX04J1UPz,Mac,[],[],parent,Do you consider yourself diligent?,scale,None,None,NaN
24115,5717665985331200,686,True,2017-01-15 00:56:07.030180+00:00,I4iPagCSYKgq3Yr43DxjEc2rcaX02dce,Nathalie,[],[],parent,"In the last week, have you spent time playing ...",scale,None,None,NaN
25266,5723846241943552,600,False,2017-01-15 00:56:07.030410+00:00,OE4MHZFRJz8NefIWu2BXkdYmLZ4NZAHL,Hazel,[no],[answer],parent,Do you want {kid_name} to do the same activiti...,scale,no,answer,no
21368,5697543191134208,587,True,2017-01-15 00:56:07.030660+00:00,GZo0GusxY78YVqrUVjd5QLE1fbSB1Aqb,Meg,[],[],parent,"For the most part, do you enjoy your daily act...",scale,None,None,NaN
34071,5844106467082240,234,True,2017-01-15 00:56:07.031030+00:00,lJhT4n44foLYJlSshT58jwXmbCMu0ceH,Sweetbear,[],[],child,Does {kid_name} know a few shapes?,scale,None,None,NaN
24298,5718264999051264,605,True,2017-01-15 00:56:07.032790+00:00,IWlQePJji4R1nhHT644SPWRVAQz7P5n2,Elisa,[yes],[answer],child,Does {kid_name} have a hard time adjusting to ...,scale,yes,answer,yes
8944,5462642772672512,288,True,2017-01-15 00:56:07.033070+00:00,J4uNcMlvm5gr99IJWpRHshoWR2DoZgp1,Annika,[yes],[answer],child,Does {kid_name} become frustrated when other c...,scale,yes,answer,yes
23813,5717264808542208,216,True,2017-01-15 00:56:07.033220+00:00,NNRae5YI8OMlYq21PW2SqDHu0sIyJoUe,Cullen,[],[],child,Does {kid_name} help get dressed or undressed?,scale,None,None,NaN
6026,5167085671940096,17,False,2017-01-15 00:56:07.033370+00:00,zlEdLFAyNdci0qZhMajaQAHj7aLVuSZM,Cecilia,[],[],parent,"In the last month, have you set a goal that wa...",scale,None,None,NaN
2231,4999681536950272,785,True,2017-01-15 00:56:07.033510+00:00,2Sn46LhrMJf1SN0XwmW4b7h7FBBV5bnk,Rowan,[yes],[answer],parent,Are you interested in learning about the peopl...,scale,yes,answer,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13433,5650886118342656,367,None,2018-11-25 18:43:07.907034+00:00,Dg880o6GfFSYTcOpgA5aYQvGSKwwWMQ3,Louis,"[yes, kid answered]","[answer, feedback]",child,Does {kid_name} attend school outside of the h...,binary,"yes, kid answered","answer, feedback",yes
13435,5650886118342656,371,None,2018-11-25 18:43:11.363193+00:00,sbbtYsp2BcLbcb4vgQjMmprhebjmqmtM,Louis,[yes],[answer],parent,Do you work outside of the home?,binary,yes,answer,yes
37538,6283284199768064,2,None,2018-11-26 00:57:39.368832+00:00,VqJbRB9abqMTBJhqcM6x2YZQbhIQVjhN,Eli,[definitely],[answer],parent,You may not be using Muse with all your kids; ...,binary,definitely,answer,definitely
24444,5720141639712768,1066,None,2018-11-26 07:39:45.472048+00:00,2vfR4Svnyvdv02dO9UqFspBoHvcW2gWf,Malou,[definitely],[answer],parent,Can you think of a time in the past month when...,binary,definitely,answer,definitely
36041,6135557054791680,1097,None,2018-11-26 15:10:45.334461+00:00,kUvpjEKIz2JYaQpHTqdxUgSsiQRbg4ko,Piper,[definitely],[answer],parent,Active play is key to learning! Do you have a ...,binary,definitely,answer,definitely
20644,5692765178429440,5,True,2018-11-26 15:53:39.057136+00:00,ktUb9XUprNPEBiKpktpbvcPiYOB1nMa6,Hunter,[],[],parent,The positive influence of early parent-to-chil...,binary,None,None,NaN
35242,6005362368970752,24,None,2018-11-26 20:03:12.047472+00:00,16262wpLpSl3rH5pc1mUqefygW9qduY5,Nathan,[definitely],[answer],parent,Do you know the name of {kid_name}'s primary d...,binary,definitely,answer,definitely
2411,5052648327741440,10,None,2018-11-26 20:15:41.466604+00:00,ABGNxKBxPbfueijhye5AkW3fqghHoRp4,Hannah,[definitely],[answer],parent,Every household is different and I want to lea...,binary,definitely,answer,definitely
29876,5750196516421632,847,None,2018-11-26 20:43:25.535846+00:00,gyibcQU5SUiteTW87HBVFyHdRYWzqCZ0,Ev,[no],[answer],parent,Are there families in your neighborhood that a...,binary,no,answer,no
2412,5052648327741440,25,None,2018-11-26 20:47:08.733711+00:00,Go2sSsPbNZ23mrAR1lZaIsKcnKWbcQic,Hannah,[definitely],[answer],parent,Does your family have health care?,binary,definitely,answer,definitely
30540,5752751367651328,368,None,2018-11-26 21:16:17.690576+00:00,nPhJCqC3PwDNyda2wQQVGqBrDimOZpQx,Lily,[not yet],[feedback],parent,Do you have reliable childcare for {kid_name}?,binary,not yet,feedback,NaN
30541,5752751367651328,371,None,2018-11-26 21:16:25.864320+00:00,AdQqHAFfnbw0dtdu28eAJueQjosufWhJ,Lily,[not yet],[feedback],parent,Do you work outside of the home?,binary,not yet,feedback,NaN
3774,5102781136371712,847,None,2018-11-26 23:37:40.039018+00:00,6C54Wj86YKzqp2WOn6R7dBzoKvXopUyy,Kaylen,[definitely],[answer],parent,Are there families in your neighborhood that a...,binary,definitely,answer,definitely
2083,4975444847755264,39,None,2018-11-27 00:24:01.167101+00:00,6tyr9oO6XXiIlBDPpMWJfUV1sia6fjaR,Callum,[definitely],[answer],parent,Did you graduate from college?,binary,definitely,answer,definitely
12082,5643161502220288,847,None,2018-11-27 02:11:30.955972+00:00,Wy7MD0GF8RVWpz3eDVDOaJ9urgjMD7mR,Finn,[yes],[answer],parent,Are there families in your neighborhood that a...,binary,yes,answer,yes
601,4776652622004224,24,None,2018-11-27 10:34:39.912430+00:00,tQNvgqsxh41BCXmBj4GA5WauWDfsy04w,Popo,"[yes, absolutely, of course]","[answer, feedback, feedback]",parent,Do you know the name of {kid_name}'s primary d...,binary,"yes, absolutely, of course","answer, feedback, feedback",yes
24413,5719302212681728,590,None,2018-11-27 14:20:06.841740+00:00,Pyd74T36YH1xfI8kdj1gnQ8SwUYDvfrv,Ilu,[definitely],[answer],parent,Do you have a primary doctor?,binary,definitely,answer,definitely
24405,5719302212681728,13,None,2018-11-27 14:20:26.356707+00:00,RdNQRxnS2UKU3jnm7nh9leUcpo5Zz5Ru,Ilu,[nope],[answer],parent,Do you know your next door neighbor's first name?,binary,nope,answer,nope
29110,5746405897404416,22,None,2018-11-27 16:59:20.441837+00:00,VbV9Ng9wcRPUE0tpCLU3WPbaBYxCbs44,Cara,[definitely],[answer],parent,Do you know where the nearest playground is fr...,binary,definitely,answer,definitely
22540,5707731738558464,38,None,2018-11-27 17:06:16.921951+00:00,kPPTFBoOie3OVkiSxYfeOBwc7Sf8CkMB,Vince,[absolutely],[feedback],parent,Did you graduate from high school?,binary,absolutely,feedback,NaN
14693,5661648199090176,42,None,2018-11-27 18:09:01.225767+00:00,Oczgt7bfKYjzH2mhtLIQZnL2n0T1o77S,Let,[nope],[answer],parent,Do you smoke?,binary,nope,answer,nope
14691,5661648199090176,367,None,2018-11-27 18:10:07.948978+00:00,HjmW1GrbptReWkpiYxhquJy1uPPBRclF,Let,[probably],[answer],child,Does {kid_name} attend school outside of the h...,binary,probably,answer,probably
14692,5661648199090176,371,None,2018-11-27 18:10:16.547343+00:00,ZC5nMDPbFzJgOPLN7nGSd4KvQVV05gz9,Let,[definitely],[answer],parent,Do you work outside of the home?,binary,definitely,answer,definitely
35643,6046364106489856,4,None,2018-11-27 22:18:31.452717+00:00,WKU4m1neWJMDeGL7kKTCEzGiHqVkx01m,Lachlan,[definitely],[answer],parent,What's your neighborhood like: are you within ...,binary,definitely,answer,definitely
35644,6046364106489856,41,None,2018-11-27 22:18:34.384637+00:00,pj8gbKsjR0aUQpVw97dAoZi99JlHIbMM,Lachlan,[nope],[answer],parent,Are you the first person in your family to gra...,binary,nope,answer,nope
32094,5762578928107520,24,None,2018-11-27 23:24:48.904958+00:00,EDDVryEobxfuKnRqxgDlup1xgMQ4PuUe,CHARLIE,[yes],[answer],parent,Do you know the name of {kid_name}'s primary d...,binary,yes,answer,yes
38186,6349348078092288,741,None,2018-11-27 23:35:37.150213+00:00,shCp0K1UGQN5Su1kPKHZiOwCt7o0RcDt,Declan,"[yes, of course, good idea, absolutely, kid an...","[answer, feedback, feedback, feedback, feedback]",child,"Does {kid_name} save money in a piggy bank, or...",binary,"yes, of course, good idea, absolutely, kid ans...","answer, feedback, feedback, feedback, feedback",yes
37031,6254170495516672,590,None,2018-11-28 02:18:06.940397+00:00,R0PsZqzIkvcyzUrV52JH4tEymjjzH2Xk,Gwen,[definitely],[answer],parent,Do you have a primary doctor?,binary,definitely,answer,definitely
37021,6254170495516672,22,None,2018-11-28 02:18:27.203607+00:00,Ac6MRT56jxbmUyzmYqAvpOHcePJgXnOe,Gwen,[definitely],[answer],parent,Do you know where the nearest playground is fr...,binary,definitely,answer,definitely
25308,5724478252253184,1099,None,2018-11-28 03:55:30.195524+00:00,hS1G2EWPxOsc4ieOWlnStE7OP85gwHIc,Edie,[no],[answer],parent,"School isn't for everyone, but maybe it was fo...",binary,no,answer,no

In [96]:
combined_df[combined_df.answer == True && combined_df.final_answer = 'yes']

SyntaxError: invalid syntax (<ipython-input-96-816f781b4627>, line 1)

In [98]:
# Dictionary for numbers
answers = {
        'yes': 1,
        'no': -1,
        'definitely': 2,
        'probably': 1,
        'somewhat': 0,
        'barely': -1,
        'nope': -2,
#         True: 1,
#         False: -1
    }

lst_all = []

for i in combined_df.index:
    learner = combined_df.at[i, 'learner']
    question = combined_df.at[i, 'question']
    question = int(question) 
    
    tup2 = (learner, question)
    
    #if tup[2] is None:
    lst_all.append(tup2)

In [101]:
len(set(lst_all))

30915

In [103]:
muse_model_df.count().sum()

30321

solution: order the combined_df by last_modified (ASC), and as the index iterator goes in order... it will automatically choose the last modified answer

In [18]:
project = 'socos-quickstep-601'
dataset_id = 'muse_matrix'
table_id = 'muse_matrix.learners_questions'

# Load job_config and define schema
job_config = bigquery.LoadJobConfig(
        schema=[
            bigquery.SchemaField("q1", "INTEGER"),
            bigquery.SchemaField("q2", "INTEGER"),
            bigquery.SchemaField("q3", "INTEGER"),
            bigquery.SchemaField("q4", "INTEGER"),
            bigquery.SchemaField("q5", "INTEGER"),
            bigquery.SchemaField("q6", "INTEGER"),
            bigquery.SchemaField("q7", "INTEGER"),
            bigquery.SchemaField("q8", "INTEGER"),
            bigquery.SchemaField("q9", "INTEGER"),
            bigquery.SchemaField("q10", "INTEGER"),
            bigquery.SchemaField("q11", "INTEGER"),
            bigquery.SchemaField("q12", "INTEGER"),
            bigquery.SchemaField("q13", "INTEGER"),
            bigquery.SchemaField("q14", "INTEGER"),
            bigquery.SchemaField("q15", "INTEGER"),
            bigquery.SchemaField("q16", "INTEGER"),
            bigquery.SchemaField("q17", "INTEGER"),
            bigquery.SchemaField("q18", "INTEGER"),
            bigquery.SchemaField("q19", "INTEGER"),
            bigquery.SchemaField("q20", "INTEGER"),
            bigquery.SchemaField("q21", "INTEGER"),
            bigquery.SchemaField("q22", "INTEGER"),
            bigquery.SchemaField("q23", "INTEGER"),
            bigquery.SchemaField("q24", "INTEGER"),
            bigquery.SchemaField("q25", "INTEGER"),
            bigquery.SchemaField("q26", "INTEGER"),
            bigquery.SchemaField("q27", "INTEGER"),
            bigquery.SchemaField("q28", "INTEGER"),
            bigquery.SchemaField("q29", "INTEGER"),
            bigquery.SchemaField("q30", "INTEGER"),
            bigquery.SchemaField("q31", "INTEGER"),
            bigquery.SchemaField("q32", "INTEGER"),
            bigquery.SchemaField("q33", "INTEGER"),
            bigquery.SchemaField("q34", "INTEGER"),
            bigquery.SchemaField("q35", "INTEGER"),
            bigquery.SchemaField("q36", "INTEGER"),
            bigquery.SchemaField("q37", "INTEGER"),
            bigquery.SchemaField("q38", "INTEGER"),
            bigquery.SchemaField("q39", "INTEGER"),
            bigquery.SchemaField("q40", "INTEGER"),
            bigquery.SchemaField("q41", "INTEGER"),
            bigquery.SchemaField("q42", "INTEGER"),
            bigquery.SchemaField("q43", "INTEGER"),
            bigquery.SchemaField("q44", "INTEGER"),
            bigquery.SchemaField("q45", "INTEGER"),
            bigquery.SchemaField("q46", "INTEGER"),
            bigquery.SchemaField("q47", "INTEGER"),
            bigquery.SchemaField("q48", "INTEGER"),
            bigquery.SchemaField("q49", "INTEGER"),
            bigquery.SchemaField("q50", "INTEGER"),
            bigquery.SchemaField("q51", "INTEGER"),
            bigquery.SchemaField("q52", "INTEGER"),
            bigquery.SchemaField("q53", "INTEGER"),
            bigquery.SchemaField("q54", "INTEGER"),
            bigquery.SchemaField("q55", "INTEGER"),
            bigquery.SchemaField("q56", "INTEGER"),
            bigquery.SchemaField("q57", "INTEGER"),
            bigquery.SchemaField("q58", "INTEGER"),
            bigquery.SchemaField("q59", "INTEGER"),
            bigquery.SchemaField("q60", "INTEGER"),
            bigquery.SchemaField("q61", "INTEGER"),
            bigquery.SchemaField("q62", "INTEGER"),
            bigquery.SchemaField("q63", "INTEGER"),
            bigquery.SchemaField("q64", "INTEGER"),
            bigquery.SchemaField("q65", "INTEGER"),
            bigquery.SchemaField("q66", "INTEGER"),
            bigquery.SchemaField("q67", "INTEGER"),
            bigquery.SchemaField("q68", "INTEGER"),
            bigquery.SchemaField("q69", "INTEGER"),
            bigquery.SchemaField("q70", "INTEGER"),
            bigquery.SchemaField("q71", "INTEGER"),
            bigquery.SchemaField("q72", "INTEGER"),
            bigquery.SchemaField("q73", "INTEGER"),
            bigquery.SchemaField("q74", "INTEGER"),
            bigquery.SchemaField("q75", "INTEGER"),
            bigquery.SchemaField("q76", "INTEGER"),
            bigquery.SchemaField("q77", "INTEGER"),
            bigquery.SchemaField("q78", "INTEGER"),
            bigquery.SchemaField("q79", "INTEGER"),
            bigquery.SchemaField("q80", "INTEGER"),
            bigquery.SchemaField("q81", "INTEGER"),
            bigquery.SchemaField("q82", "INTEGER"),
            bigquery.SchemaField("q83", "INTEGER"),
            bigquery.SchemaField("q84", "INTEGER"),
            bigquery.SchemaField("q85", "INTEGER"),
            bigquery.SchemaField("q86", "INTEGER"),
            bigquery.SchemaField("q87", "INTEGER"),
            bigquery.SchemaField("q88", "INTEGER"),
            bigquery.SchemaField("q89", "INTEGER"),
            bigquery.SchemaField("q90", "INTEGER"),
            bigquery.SchemaField("q91", "INTEGER"),
            bigquery.SchemaField("q92", "INTEGER"),
            bigquery.SchemaField("q93", "INTEGER"),
            bigquery.SchemaField("q94", "INTEGER"),
            bigquery.SchemaField("q95", "INTEGER"),
            bigquery.SchemaField("q96", "INTEGER"),
            bigquery.SchemaField("q97", "INTEGER"),
            bigquery.SchemaField("q98", "INTEGER"),
            bigquery.SchemaField("q99", "INTEGER"),
            bigquery.SchemaField("q100", "INTEGER"),
            bigquery.SchemaField("q101", "INTEGER"),
            bigquery.SchemaField("q102", "INTEGER"),
            bigquery.SchemaField("q103", "INTEGER"),
            bigquery.SchemaField("q104", "INTEGER"),
            bigquery.SchemaField("q105", "INTEGER"),
            bigquery.SchemaField("q106", "INTEGER"),
            bigquery.SchemaField("q107", "INTEGER"),
            bigquery.SchemaField("q108", "INTEGER"),
            bigquery.SchemaField("q109", "INTEGER"),
            bigquery.SchemaField("q110", "INTEGER"),
            bigquery.SchemaField("q111", "INTEGER"),
            bigquery.SchemaField("q112", "INTEGER"),
            bigquery.SchemaField("q113", "INTEGER"),
            bigquery.SchemaField("q114", "INTEGER"),
            bigquery.SchemaField("q115", "INTEGER"),
            bigquery.SchemaField("q116", "INTEGER"),
            bigquery.SchemaField("q117", "INTEGER"),
            bigquery.SchemaField("q118", "INTEGER"),
            bigquery.SchemaField("q119", "INTEGER"),
            bigquery.SchemaField("q120", "INTEGER"),
            bigquery.SchemaField("q121", "INTEGER"),
            bigquery.SchemaField("q122", "INTEGER"),
            bigquery.SchemaField("q123", "INTEGER"),
            bigquery.SchemaField("q124", "INTEGER"),
            bigquery.SchemaField("q125", "INTEGER"),
            bigquery.SchemaField("q126", "INTEGER"),
            bigquery.SchemaField("q127", "INTEGER"),
            bigquery.SchemaField("q128", "INTEGER"),
            bigquery.SchemaField("q129", "INTEGER"),
            bigquery.SchemaField("q130", "INTEGER"),
            bigquery.SchemaField("q131", "INTEGER"),
            bigquery.SchemaField("q132", "INTEGER"),
            bigquery.SchemaField("q133", "INTEGER"),
            bigquery.SchemaField("q134", "INTEGER"),
            bigquery.SchemaField("q135", "INTEGER"),
            bigquery.SchemaField("q136", "INTEGER"),
            bigquery.SchemaField("q137", "INTEGER"),
            bigquery.SchemaField("q138", "INTEGER"),
            bigquery.SchemaField("q139", "INTEGER"),
            bigquery.SchemaField("q140", "INTEGER"),
            bigquery.SchemaField("q141", "INTEGER"),
            bigquery.SchemaField("q142", "INTEGER"),
            bigquery.SchemaField("q143", "INTEGER"),
            bigquery.SchemaField("q144", "INTEGER"),
            bigquery.SchemaField("q145", "INTEGER"),
            bigquery.SchemaField("q146", "INTEGER"),
            bigquery.SchemaField("q147", "INTEGER"),
            bigquery.SchemaField("q148", "INTEGER"),
            bigquery.SchemaField("q149", "INTEGER"),
            bigquery.SchemaField("q150", "INTEGER"),
            bigquery.SchemaField("q151", "INTEGER"),
            bigquery.SchemaField("q152", "INTEGER"),
            bigquery.SchemaField("q153", "INTEGER"),
            bigquery.SchemaField("q154", "INTEGER"),
            bigquery.SchemaField("q155", "INTEGER"),
            bigquery.SchemaField("q156", "INTEGER"),
            bigquery.SchemaField("q157", "INTEGER"),
            bigquery.SchemaField("q158", "INTEGER"),
            bigquery.SchemaField("q159", "INTEGER"),
            bigquery.SchemaField("q160", "INTEGER"),
            bigquery.SchemaField("q161", "INTEGER"),
            bigquery.SchemaField("q162", "INTEGER"),
            bigquery.SchemaField("q163", "INTEGER"),
            bigquery.SchemaField("q164", "INTEGER"),
            bigquery.SchemaField("q165", "INTEGER"),
            bigquery.SchemaField("q166", "INTEGER"),
            bigquery.SchemaField("q167", "INTEGER"),
            bigquery.SchemaField("q168", "INTEGER"),
            bigquery.SchemaField("q169", "INTEGER"),
            bigquery.SchemaField("q170", "INTEGER"),
            bigquery.SchemaField("q171", "INTEGER"),
            bigquery.SchemaField("q172", "INTEGER"),
            bigquery.SchemaField("q173", "INTEGER"),
            bigquery.SchemaField("q174", "INTEGER"),
            bigquery.SchemaField("q175", "INTEGER"),
            bigquery.SchemaField("q176", "INTEGER"),
            bigquery.SchemaField("q177", "INTEGER"),
            bigquery.SchemaField("q178", "INTEGER"),
            bigquery.SchemaField("q179", "INTEGER"),
            bigquery.SchemaField("q180", "INTEGER"),
            bigquery.SchemaField("q181", "INTEGER"),
            bigquery.SchemaField("q182", "INTEGER"),
            bigquery.SchemaField("q183", "INTEGER"),
            bigquery.SchemaField("q184", "INTEGER"),
            bigquery.SchemaField("q185", "INTEGER"),
            bigquery.SchemaField("q186", "INTEGER"),
            bigquery.SchemaField("q187", "INTEGER"),
            bigquery.SchemaField("q188", "INTEGER"),
            bigquery.SchemaField("q189", "INTEGER"),
            bigquery.SchemaField("q190", "INTEGER"),
            bigquery.SchemaField("q191", "INTEGER"),
            bigquery.SchemaField("q192", "INTEGER"),
            bigquery.SchemaField("q193", "INTEGER"),
            bigquery.SchemaField("q194", "INTEGER"),
            bigquery.SchemaField("q195", "INTEGER"),
            bigquery.SchemaField("q196", "INTEGER"),
            bigquery.SchemaField("q197", "INTEGER"),
            bigquery.SchemaField("q198", "INTEGER"),
            bigquery.SchemaField("q199", "INTEGER"),
            bigquery.SchemaField("q200", "INTEGER"),
            bigquery.SchemaField("q201", "INTEGER"),
            bigquery.SchemaField("q202", "INTEGER"),
            bigquery.SchemaField("q203", "INTEGER"),
            bigquery.SchemaField("q204", "INTEGER"),
            bigquery.SchemaField("q205", "INTEGER"),
            bigquery.SchemaField("q206", "INTEGER"),
            bigquery.SchemaField("q207", "INTEGER"),
            bigquery.SchemaField("q208", "INTEGER"),
            bigquery.SchemaField("q209", "INTEGER"),
            bigquery.SchemaField("q210", "INTEGER"),
            bigquery.SchemaField("q211", "INTEGER"),
            bigquery.SchemaField("q212", "INTEGER"),
            bigquery.SchemaField("q213", "INTEGER"),
            bigquery.SchemaField("q214", "INTEGER"),
            bigquery.SchemaField("q215", "INTEGER"),
            bigquery.SchemaField("q216", "INTEGER"),
            bigquery.SchemaField("q217", "INTEGER"),
            bigquery.SchemaField("q218", "INTEGER"),
            bigquery.SchemaField("q219", "INTEGER"),
            bigquery.SchemaField("q220", "INTEGER"),
            bigquery.SchemaField("q221", "INTEGER"),
            bigquery.SchemaField("q222", "INTEGER"),
            bigquery.SchemaField("q223", "INTEGER"),
            bigquery.SchemaField("q224", "INTEGER"),
            bigquery.SchemaField("q225", "INTEGER"),
            bigquery.SchemaField("q226", "INTEGER"),
            bigquery.SchemaField("q227", "INTEGER"),
            bigquery.SchemaField("q228", "INTEGER"),
            bigquery.SchemaField("q229", "INTEGER"),
            bigquery.SchemaField("q230", "INTEGER"),
            bigquery.SchemaField("q231", "INTEGER"),
            bigquery.SchemaField("q232", "INTEGER"),
            bigquery.SchemaField("q233", "INTEGER"),
            bigquery.SchemaField("q234", "INTEGER"),
            bigquery.SchemaField("q235", "INTEGER"),
            bigquery.SchemaField("q236", "INTEGER"),
            bigquery.SchemaField("q237", "INTEGER"),
            bigquery.SchemaField("q238", "INTEGER"),
            bigquery.SchemaField("q239", "INTEGER"),
            bigquery.SchemaField("q240", "INTEGER"),
            bigquery.SchemaField("q241", "INTEGER"),
            bigquery.SchemaField("q242", "INTEGER"),
            bigquery.SchemaField("q243", "INTEGER"),
            bigquery.SchemaField("q244", "INTEGER"),
            bigquery.SchemaField("q245", "INTEGER"),
            bigquery.SchemaField("q246", "INTEGER"),
            bigquery.SchemaField("q247", "INTEGER"),
            bigquery.SchemaField("q248", "INTEGER"),
            bigquery.SchemaField("q249", "INTEGER"),
            bigquery.SchemaField("q250", "INTEGER"),
            bigquery.SchemaField("q251", "INTEGER"),
            bigquery.SchemaField("q252", "INTEGER"),
            bigquery.SchemaField("q253", "INTEGER"),
            bigquery.SchemaField("q254", "INTEGER"),
            bigquery.SchemaField("q255", "INTEGER"),
            bigquery.SchemaField("q256", "INTEGER"),
            bigquery.SchemaField("q257", "INTEGER"),
            bigquery.SchemaField("q258", "INTEGER"),
            bigquery.SchemaField("q259", "INTEGER"),
            bigquery.SchemaField("q260", "INTEGER"),
            bigquery.SchemaField("q261", "INTEGER"),
            bigquery.SchemaField("q262", "INTEGER"),
            bigquery.SchemaField("q263", "INTEGER"),
            bigquery.SchemaField("q264", "INTEGER"),
            bigquery.SchemaField("q265", "INTEGER"),
            bigquery.SchemaField("q266", "INTEGER"),
            bigquery.SchemaField("q267", "INTEGER"),
            bigquery.SchemaField("q268", "INTEGER"),
            bigquery.SchemaField("q269", "INTEGER"),
            bigquery.SchemaField("q270", "INTEGER"),
            bigquery.SchemaField("q271", "INTEGER"),
            bigquery.SchemaField("q272", "INTEGER"),
            bigquery.SchemaField("q273", "INTEGER"),
            bigquery.SchemaField("q274", "INTEGER"),
            bigquery.SchemaField("q275", "INTEGER"),
            bigquery.SchemaField("q276", "INTEGER"),
            bigquery.SchemaField("q277", "INTEGER"),
            bigquery.SchemaField("q278", "INTEGER"),
            bigquery.SchemaField("q279", "INTEGER"),
            bigquery.SchemaField("q280", "INTEGER"),
            bigquery.SchemaField("q281", "INTEGER"),
            bigquery.SchemaField("q282", "INTEGER"),
            bigquery.SchemaField("q283", "INTEGER"),
            bigquery.SchemaField("q284", "INTEGER"),
            bigquery.SchemaField("q285", "INTEGER"),
            bigquery.SchemaField("q286", "INTEGER"),
            bigquery.SchemaField("q287", "INTEGER"),
            bigquery.SchemaField("q288", "INTEGER"),
            bigquery.SchemaField("q289", "INTEGER"),
            bigquery.SchemaField("q290", "INTEGER"),
            bigquery.SchemaField("q291", "INTEGER"),
            bigquery.SchemaField("q292", "INTEGER"),
            bigquery.SchemaField("q293", "INTEGER"),
            bigquery.SchemaField("q294", "INTEGER"),
            bigquery.SchemaField("q295", "INTEGER"),
            bigquery.SchemaField("q296", "INTEGER"),
            bigquery.SchemaField("q297", "INTEGER"),
            bigquery.SchemaField("q298", "INTEGER"),
            bigquery.SchemaField("q299", "INTEGER"),
            bigquery.SchemaField("q300", "INTEGER"),
            bigquery.SchemaField("q301", "INTEGER"),
            bigquery.SchemaField("q302", "INTEGER"),
            bigquery.SchemaField("q303", "INTEGER"),
            bigquery.SchemaField("q304", "INTEGER"),
            bigquery.SchemaField("q305", "INTEGER"),
            bigquery.SchemaField("q306", "INTEGER"),
            bigquery.SchemaField("q307", "INTEGER"),
            bigquery.SchemaField("q308", "INTEGER"),
            bigquery.SchemaField("q309", "INTEGER"),
            bigquery.SchemaField("q310", "INTEGER"),
            bigquery.SchemaField("q311", "INTEGER"),
            bigquery.SchemaField("q312", "INTEGER"),
            bigquery.SchemaField("q313", "INTEGER"),
            bigquery.SchemaField("q314", "INTEGER"),
            bigquery.SchemaField("q315", "INTEGER"),
            bigquery.SchemaField("q316", "INTEGER"),
            bigquery.SchemaField("q317", "INTEGER"),
            bigquery.SchemaField("q318", "INTEGER"),
            bigquery.SchemaField("q319", "INTEGER"),
            bigquery.SchemaField("q320", "INTEGER"),
            bigquery.SchemaField("q321", "INTEGER"),
            bigquery.SchemaField("q322", "INTEGER"),
            bigquery.SchemaField("q323", "INTEGER"),
            bigquery.SchemaField("q324", "INTEGER"),
            bigquery.SchemaField("q325", "INTEGER"),
            bigquery.SchemaField("q326", "INTEGER"),
            bigquery.SchemaField("q327", "INTEGER"),
            bigquery.SchemaField("q328", "INTEGER"),
            bigquery.SchemaField("q329", "INTEGER"),
            bigquery.SchemaField("q330", "INTEGER"),
            bigquery.SchemaField("q331", "INTEGER"),
            bigquery.SchemaField("q332", "INTEGER"),
            bigquery.SchemaField("q333", "INTEGER"),
            bigquery.SchemaField("q334", "INTEGER"),
            bigquery.SchemaField("q335", "INTEGER"),
            bigquery.SchemaField("q336", "INTEGER"),
            bigquery.SchemaField("q337", "INTEGER"),
            bigquery.SchemaField("q338", "INTEGER"),
            bigquery.SchemaField("q339", "INTEGER"),
            bigquery.SchemaField("q340", "INTEGER"),
            bigquery.SchemaField("q341", "INTEGER"),
            bigquery.SchemaField("q342", "INTEGER"),
            bigquery.SchemaField("q343", "INTEGER"),
            bigquery.SchemaField("q344", "INTEGER"),
            bigquery.SchemaField("q345", "INTEGER"),
            bigquery.SchemaField("q346", "INTEGER"),
            bigquery.SchemaField("q347", "INTEGER"),
            bigquery.SchemaField("q348", "INTEGER"),
            bigquery.SchemaField("q349", "INTEGER"),
            bigquery.SchemaField("q350", "INTEGER"),
            bigquery.SchemaField("q351", "INTEGER"),
            bigquery.SchemaField("q352", "INTEGER"),
            bigquery.SchemaField("q353", "INTEGER"),
            bigquery.SchemaField("q354", "INTEGER"),
            bigquery.SchemaField("q355", "INTEGER"),
            bigquery.SchemaField("q356", "INTEGER"),
            bigquery.SchemaField("q357", "INTEGER"),
            bigquery.SchemaField("q358", "INTEGER"),
            bigquery.SchemaField("q359", "INTEGER"),
            bigquery.SchemaField("q360", "INTEGER"),
            bigquery.SchemaField("q361", "INTEGER"),
            bigquery.SchemaField("q362", "INTEGER"),
            bigquery.SchemaField("q363", "INTEGER"),
            bigquery.SchemaField("q364", "INTEGER"),
            bigquery.SchemaField("q365", "INTEGER"),
            bigquery.SchemaField("q366", "INTEGER"),
            bigquery.SchemaField("q367", "INTEGER"),
            bigquery.SchemaField("q368", "INTEGER"),
            bigquery.SchemaField("q369", "INTEGER"),
            bigquery.SchemaField("q370", "INTEGER"),
            bigquery.SchemaField("q371", "INTEGER"),
            bigquery.SchemaField("q372", "INTEGER"),
            bigquery.SchemaField("q373", "INTEGER"),
            bigquery.SchemaField("q374", "INTEGER"),
            bigquery.SchemaField("q375", "INTEGER"),
            bigquery.SchemaField("q376", "INTEGER"),
            bigquery.SchemaField("q377", "INTEGER"),
            bigquery.SchemaField("q378", "INTEGER"),
            bigquery.SchemaField("q379", "INTEGER"),
            bigquery.SchemaField("q380", "INTEGER"),
            bigquery.SchemaField("q381", "INTEGER"),
            bigquery.SchemaField("q382", "INTEGER"),
            bigquery.SchemaField("q383", "INTEGER"),
            bigquery.SchemaField("q384", "INTEGER"),
            bigquery.SchemaField("q385", "INTEGER"),
            bigquery.SchemaField("q386", "INTEGER"),
            bigquery.SchemaField("q387", "INTEGER"),
            bigquery.SchemaField("q388", "INTEGER"),
            bigquery.SchemaField("q389", "INTEGER"),
            bigquery.SchemaField("q390", "INTEGER"),
            bigquery.SchemaField("q391", "INTEGER"),
            bigquery.SchemaField("q392", "INTEGER"),
            bigquery.SchemaField("q393", "INTEGER"),
            bigquery.SchemaField("q394", "INTEGER"),
            bigquery.SchemaField("q395", "INTEGER"),
            bigquery.SchemaField("q396", "INTEGER"),
            bigquery.SchemaField("q397", "INTEGER"),
            bigquery.SchemaField("q398", "INTEGER"),
            bigquery.SchemaField("q399", "INTEGER"),
            bigquery.SchemaField("q400", "INTEGER"),
            bigquery.SchemaField("q401", "INTEGER"),
            bigquery.SchemaField("q402", "INTEGER"),
            bigquery.SchemaField("q403", "INTEGER"),
            bigquery.SchemaField("q404", "INTEGER"),
            bigquery.SchemaField("q405", "INTEGER"),
            bigquery.SchemaField("q406", "INTEGER"),
            bigquery.SchemaField("q407", "INTEGER"),
            bigquery.SchemaField("q408", "INTEGER"),
            bigquery.SchemaField("q409", "INTEGER"),
            bigquery.SchemaField("q410", "INTEGER"),
            bigquery.SchemaField("q411", "INTEGER"),
            bigquery.SchemaField("q412", "INTEGER"),
            bigquery.SchemaField("q413", "INTEGER"),
            bigquery.SchemaField("q414", "INTEGER"),
            bigquery.SchemaField("q415", "INTEGER"),
            bigquery.SchemaField("q416", "INTEGER"),
            bigquery.SchemaField("q417", "INTEGER"),
            bigquery.SchemaField("q418", "INTEGER"),
            bigquery.SchemaField("q419", "INTEGER"),
            bigquery.SchemaField("q420", "INTEGER"),
            bigquery.SchemaField("q421", "INTEGER"),
            bigquery.SchemaField("q422", "INTEGER"),
            bigquery.SchemaField("q423", "INTEGER"),
            bigquery.SchemaField("q424", "INTEGER"),
            bigquery.SchemaField("q425", "INTEGER"),
            bigquery.SchemaField("q426", "INTEGER"),
            bigquery.SchemaField("q427", "INTEGER"),
            bigquery.SchemaField("q428", "INTEGER"),
            bigquery.SchemaField("q429", "INTEGER"),
            bigquery.SchemaField("q430", "INTEGER"),
            bigquery.SchemaField("q431", "INTEGER"),
            bigquery.SchemaField("q432", "INTEGER"),
            bigquery.SchemaField("q433", "INTEGER"),
            bigquery.SchemaField("q434", "INTEGER"),
            bigquery.SchemaField("q435", "INTEGER"),
            bigquery.SchemaField("q436", "INTEGER"),
            bigquery.SchemaField("q437", "INTEGER"),
            bigquery.SchemaField("q438", "INTEGER"),
            bigquery.SchemaField("q439", "INTEGER"),
            bigquery.SchemaField("q440", "INTEGER"),
            bigquery.SchemaField("q441", "INTEGER"),
            bigquery.SchemaField("q442", "INTEGER"),
            bigquery.SchemaField("q443", "INTEGER"),
            bigquery.SchemaField("q444", "INTEGER"),
            bigquery.SchemaField("q445", "INTEGER"),
            bigquery.SchemaField("q446", "INTEGER"),
            bigquery.SchemaField("q447", "INTEGER"),
            bigquery.SchemaField("q448", "INTEGER"),
            bigquery.SchemaField("q449", "INTEGER"),
            bigquery.SchemaField("q450", "INTEGER"),
            bigquery.SchemaField("q451", "INTEGER"),
            bigquery.SchemaField("q452", "INTEGER"),
            bigquery.SchemaField("q453", "INTEGER"),
            bigquery.SchemaField("q454", "INTEGER"),
            bigquery.SchemaField("q455", "INTEGER"),
            bigquery.SchemaField("q456", "INTEGER"),
            bigquery.SchemaField("q457", "INTEGER"),
            bigquery.SchemaField("q458", "INTEGER"),
            bigquery.SchemaField("q459", "INTEGER"),
            bigquery.SchemaField("q460", "INTEGER"),
            bigquery.SchemaField("q461", "INTEGER"),
            bigquery.SchemaField("q462", "INTEGER"),
            bigquery.SchemaField("q463", "INTEGER"),
            bigquery.SchemaField("q464", "INTEGER"),
            bigquery.SchemaField("q465", "INTEGER"),
            bigquery.SchemaField("q466", "INTEGER"),
            bigquery.SchemaField("q467", "INTEGER"),
            bigquery.SchemaField("q468", "INTEGER"),
            bigquery.SchemaField("q469", "INTEGER"),
            bigquery.SchemaField("q470", "INTEGER"),
            bigquery.SchemaField("q471", "INTEGER"),
            bigquery.SchemaField("q472", "INTEGER"),
            bigquery.SchemaField("q473", "INTEGER"),
            bigquery.SchemaField("q474", "INTEGER"),
            bigquery.SchemaField("q475", "INTEGER"),
            bigquery.SchemaField("q476", "INTEGER"),
            bigquery.SchemaField("q477", "INTEGER"),
            bigquery.SchemaField("q478", "INTEGER"),
            bigquery.SchemaField("q479", "INTEGER"),
            bigquery.SchemaField("q480", "INTEGER"),
            bigquery.SchemaField("q481", "INTEGER"),
            bigquery.SchemaField("q482", "INTEGER"),
            bigquery.SchemaField("q483", "INTEGER"),
            bigquery.SchemaField("q484", "INTEGER"),
            bigquery.SchemaField("q485", "INTEGER"),
            bigquery.SchemaField("q486", "INTEGER"),
            bigquery.SchemaField("q487", "INTEGER"),
            bigquery.SchemaField("q488", "INTEGER"),
            bigquery.SchemaField("q489", "INTEGER"),
            bigquery.SchemaField("q490", "INTEGER"),
            bigquery.SchemaField("q491", "INTEGER"),
            bigquery.SchemaField("q492", "INTEGER"),
            bigquery.SchemaField("q493", "INTEGER"),
            bigquery.SchemaField("q494", "INTEGER"),
            bigquery.SchemaField("q495", "INTEGER"),
            bigquery.SchemaField("q496", "INTEGER"),
            bigquery.SchemaField("q497", "INTEGER"),
            bigquery.SchemaField("q498", "INTEGER"),
            bigquery.SchemaField("q499", "INTEGER"),
            bigquery.SchemaField("q500", "INTEGER"),
            bigquery.SchemaField("q501", "INTEGER"),
            bigquery.SchemaField("q502", "INTEGER"),
            bigquery.SchemaField("q503", "INTEGER"),
            bigquery.SchemaField("q504", "INTEGER"),
            bigquery.SchemaField("q505", "INTEGER"),
            bigquery.SchemaField("q506", "INTEGER"),
            bigquery.SchemaField("q507", "INTEGER"),
            bigquery.SchemaField("q508", "INTEGER"),
            bigquery.SchemaField("q509", "INTEGER"),
            bigquery.SchemaField("q510", "INTEGER"),
            bigquery.SchemaField("q511", "INTEGER"),
            bigquery.SchemaField("q512", "INTEGER"),
            bigquery.SchemaField("q513", "INTEGER"),
            bigquery.SchemaField("q514", "INTEGER"),
            bigquery.SchemaField("q515", "INTEGER"),
            bigquery.SchemaField("q516", "INTEGER"),
            bigquery.SchemaField("q517", "INTEGER"),
            bigquery.SchemaField("q518", "INTEGER"),
            bigquery.SchemaField("q519", "INTEGER"),
            bigquery.SchemaField("q520", "INTEGER"),
            bigquery.SchemaField("q521", "INTEGER"),
            bigquery.SchemaField("q522", "INTEGER"),
            bigquery.SchemaField("q523", "INTEGER"),
            bigquery.SchemaField("q524", "INTEGER"),
            bigquery.SchemaField("q525", "INTEGER"),
            bigquery.SchemaField("q526", "INTEGER"),
            bigquery.SchemaField("q527", "INTEGER"),
            bigquery.SchemaField("q528", "INTEGER"),
            bigquery.SchemaField("q529", "INTEGER"),
            bigquery.SchemaField("q530", "INTEGER"),
            bigquery.SchemaField("q531", "INTEGER"),
            bigquery.SchemaField("q532", "INTEGER"),
            bigquery.SchemaField("q533", "INTEGER"),
            bigquery.SchemaField("q534", "INTEGER"),
            bigquery.SchemaField("q535", "INTEGER"),
            bigquery.SchemaField("q536", "INTEGER"),
            bigquery.SchemaField("q537", "INTEGER"),
            bigquery.SchemaField("q538", "INTEGER"),
            bigquery.SchemaField("q539", "INTEGER"),
            bigquery.SchemaField("q540", "INTEGER"),
            bigquery.SchemaField("q541", "INTEGER"),
            bigquery.SchemaField("q542", "INTEGER"),
            bigquery.SchemaField("q543", "INTEGER"),
            bigquery.SchemaField("q544", "INTEGER"),
            bigquery.SchemaField("q545", "INTEGER"),
            bigquery.SchemaField("q546", "INTEGER"),
            bigquery.SchemaField("q547", "INTEGER"),
            bigquery.SchemaField("q548", "INTEGER"),
            bigquery.SchemaField("q549", "INTEGER"),
            bigquery.SchemaField("q550", "INTEGER"),
            bigquery.SchemaField("q551", "INTEGER"),
            bigquery.SchemaField("q552", "INTEGER"),
            bigquery.SchemaField("q553", "INTEGER"),
            bigquery.SchemaField("q554", "INTEGER"),
            bigquery.SchemaField("q555", "INTEGER"),
            bigquery.SchemaField("q556", "INTEGER"),
            bigquery.SchemaField("q557", "INTEGER"),
            bigquery.SchemaField("q558", "INTEGER"),
            bigquery.SchemaField("q559", "INTEGER"),
            bigquery.SchemaField("q560", "INTEGER"),
            bigquery.SchemaField("q561", "INTEGER"),
            bigquery.SchemaField("q562", "INTEGER"),
            bigquery.SchemaField("q563", "INTEGER"),
            bigquery.SchemaField("q564", "INTEGER"),
            bigquery.SchemaField("q565", "INTEGER"),
            bigquery.SchemaField("q566", "INTEGER"),
            bigquery.SchemaField("q567", "INTEGER"),
            bigquery.SchemaField("q568", "INTEGER"),
            bigquery.SchemaField("q569", "INTEGER"),
            bigquery.SchemaField("q570", "INTEGER"),
            bigquery.SchemaField("q571", "INTEGER"),
            bigquery.SchemaField("q572", "INTEGER"),
            bigquery.SchemaField("q573", "INTEGER"),
            bigquery.SchemaField("q574", "INTEGER"),
            bigquery.SchemaField("q575", "INTEGER"),
            bigquery.SchemaField("q576", "INTEGER"),
            bigquery.SchemaField("q577", "INTEGER"),
            bigquery.SchemaField("q578", "INTEGER"),
            bigquery.SchemaField("q579", "INTEGER"),
            bigquery.SchemaField("q580", "INTEGER"),
            bigquery.SchemaField("q581", "INTEGER"),
            bigquery.SchemaField("q582", "INTEGER"),
            bigquery.SchemaField("q583", "INTEGER"),
            bigquery.SchemaField("q584", "INTEGER"),
            bigquery.SchemaField("q585", "INTEGER"),
            bigquery.SchemaField("q586", "INTEGER"),
            bigquery.SchemaField("q587", "INTEGER"),
            bigquery.SchemaField("q588", "INTEGER"),
            bigquery.SchemaField("q589", "INTEGER"),
            bigquery.SchemaField("q590", "INTEGER"),
            bigquery.SchemaField("q591", "INTEGER"),
            bigquery.SchemaField("q592", "INTEGER"),
            bigquery.SchemaField("q593", "INTEGER"),
            bigquery.SchemaField("q594", "INTEGER"),
            bigquery.SchemaField("q595", "INTEGER"),
            bigquery.SchemaField("q596", "INTEGER"),
            bigquery.SchemaField("q597", "INTEGER"),
            bigquery.SchemaField("q598", "INTEGER"),
            bigquery.SchemaField("q599", "INTEGER"),
            bigquery.SchemaField("q600", "INTEGER"),
            bigquery.SchemaField("q601", "INTEGER"),
            bigquery.SchemaField("q602", "INTEGER"),
            bigquery.SchemaField("q603", "INTEGER"),
            bigquery.SchemaField("q604", "INTEGER"),
            bigquery.SchemaField("q605", "INTEGER"),
            bigquery.SchemaField("q606", "INTEGER"),
            bigquery.SchemaField("q607", "INTEGER"),
            bigquery.SchemaField("q608", "INTEGER"),
            bigquery.SchemaField("q609", "INTEGER"),
            bigquery.SchemaField("q610", "INTEGER"),
            bigquery.SchemaField("q611", "INTEGER"),
            bigquery.SchemaField("q612", "INTEGER"),
            bigquery.SchemaField("q613", "INTEGER"),
            bigquery.SchemaField("q614", "INTEGER"),
            bigquery.SchemaField("q615", "INTEGER"),
            bigquery.SchemaField("q616", "INTEGER"),
            bigquery.SchemaField("q617", "INTEGER"),
            bigquery.SchemaField("q618", "INTEGER"),
            bigquery.SchemaField("q619", "INTEGER"),
            bigquery.SchemaField("q620", "INTEGER"),
            bigquery.SchemaField("q621", "INTEGER"),
            bigquery.SchemaField("q622", "INTEGER"),
            bigquery.SchemaField("q623", "INTEGER"),
            bigquery.SchemaField("q624", "INTEGER"),
            bigquery.SchemaField("q625", "INTEGER"),
            bigquery.SchemaField("q626", "INTEGER"),
            bigquery.SchemaField("q627", "INTEGER"),
            bigquery.SchemaField("q628", "INTEGER"),
            bigquery.SchemaField("q629", "INTEGER"),
            bigquery.SchemaField("q630", "INTEGER"),
            bigquery.SchemaField("q631", "INTEGER"),
            bigquery.SchemaField("q632", "INTEGER"),
            bigquery.SchemaField("q633", "INTEGER"),
            bigquery.SchemaField("q634", "INTEGER"),
            bigquery.SchemaField("q635", "INTEGER"),
            bigquery.SchemaField("q636", "INTEGER"),
            bigquery.SchemaField("q637", "INTEGER"),
            bigquery.SchemaField("q638", "INTEGER"),
            bigquery.SchemaField("q639", "INTEGER"),
            bigquery.SchemaField("q640", "INTEGER"),
            bigquery.SchemaField("q641", "INTEGER"),
            bigquery.SchemaField("q642", "INTEGER"),
            bigquery.SchemaField("q643", "INTEGER"),
            bigquery.SchemaField("q644", "INTEGER"),
            bigquery.SchemaField("q645", "INTEGER"),
            bigquery.SchemaField("q646", "INTEGER"),
            bigquery.SchemaField("q647", "INTEGER"),
            bigquery.SchemaField("q648", "INTEGER"),
            bigquery.SchemaField("q649", "INTEGER"),
            bigquery.SchemaField("q650", "INTEGER"),
            bigquery.SchemaField("q651", "INTEGER"),
            bigquery.SchemaField("q652", "INTEGER"),
            bigquery.SchemaField("q653", "INTEGER"),
            bigquery.SchemaField("q654", "INTEGER"),
            bigquery.SchemaField("q655", "INTEGER"),
            bigquery.SchemaField("q656", "INTEGER"),
            bigquery.SchemaField("q657", "INTEGER"),
            bigquery.SchemaField("q658", "INTEGER"),
            bigquery.SchemaField("q659", "INTEGER"),
            bigquery.SchemaField("q660", "INTEGER"),
            bigquery.SchemaField("q661", "INTEGER"),
            bigquery.SchemaField("q662", "INTEGER"),
            bigquery.SchemaField("q663", "INTEGER"),
            bigquery.SchemaField("q664", "INTEGER"),
            bigquery.SchemaField("q665", "INTEGER"),
            bigquery.SchemaField("q666", "INTEGER"),
            bigquery.SchemaField("q667", "INTEGER"),
            bigquery.SchemaField("q668", "INTEGER"),
            bigquery.SchemaField("q669", "INTEGER"),
            bigquery.SchemaField("q670", "INTEGER"),
            bigquery.SchemaField("q671", "INTEGER"),
            bigquery.SchemaField("q672", "INTEGER"),
            bigquery.SchemaField("q673", "INTEGER"),
            bigquery.SchemaField("q674", "INTEGER"),
            bigquery.SchemaField("q675", "INTEGER"),
            bigquery.SchemaField("q676", "INTEGER"),
            bigquery.SchemaField("q677", "INTEGER"),
            bigquery.SchemaField("q678", "INTEGER"),
            bigquery.SchemaField("q679", "INTEGER"),
            bigquery.SchemaField("q680", "INTEGER"),
            bigquery.SchemaField("q681", "INTEGER"),
            bigquery.SchemaField("q682", "INTEGER"),
            bigquery.SchemaField("q683", "INTEGER"),
            bigquery.SchemaField("q684", "INTEGER"),
            bigquery.SchemaField("q685", "INTEGER"),
            bigquery.SchemaField("q686", "INTEGER"),
            bigquery.SchemaField("q687", "INTEGER"),
            bigquery.SchemaField("q688", "INTEGER"),
            bigquery.SchemaField("q689", "INTEGER"),
            bigquery.SchemaField("q690", "INTEGER"),
            bigquery.SchemaField("q691", "INTEGER"),
            bigquery.SchemaField("q692", "INTEGER"),
            bigquery.SchemaField("q693", "INTEGER"),
            bigquery.SchemaField("q694", "INTEGER"),
            bigquery.SchemaField("q695", "INTEGER"),
            bigquery.SchemaField("q696", "INTEGER"),
            bigquery.SchemaField("q697", "INTEGER"),
            bigquery.SchemaField("q698", "INTEGER"),
            bigquery.SchemaField("q699", "INTEGER"),
            bigquery.SchemaField("q700", "INTEGER"),
            bigquery.SchemaField("q701", "INTEGER"),
            bigquery.SchemaField("q702", "INTEGER"),
            bigquery.SchemaField("q703", "INTEGER"),
            bigquery.SchemaField("q704", "INTEGER"),
            bigquery.SchemaField("q705", "INTEGER"),
            bigquery.SchemaField("q706", "INTEGER"),
            bigquery.SchemaField("q707", "INTEGER"),
            bigquery.SchemaField("q708", "INTEGER"),
            bigquery.SchemaField("q709", "INTEGER"),
            bigquery.SchemaField("q710", "INTEGER"),
            bigquery.SchemaField("q711", "INTEGER"),
            bigquery.SchemaField("q712", "INTEGER"),
            bigquery.SchemaField("q713", "INTEGER"),
            bigquery.SchemaField("q714", "INTEGER"),
            bigquery.SchemaField("q715", "INTEGER"),
            bigquery.SchemaField("q716", "INTEGER"),
            bigquery.SchemaField("q717", "INTEGER"),
            bigquery.SchemaField("q718", "INTEGER"),
            bigquery.SchemaField("q719", "INTEGER"),
            bigquery.SchemaField("q720", "INTEGER"),
            bigquery.SchemaField("q721", "INTEGER"),
            bigquery.SchemaField("q722", "INTEGER"),
            bigquery.SchemaField("q723", "INTEGER"),
            bigquery.SchemaField("q724", "INTEGER"),
            bigquery.SchemaField("q725", "INTEGER"),
            bigquery.SchemaField("q726", "INTEGER"),
            bigquery.SchemaField("q727", "INTEGER"),
            bigquery.SchemaField("q728", "INTEGER"),
            bigquery.SchemaField("q729", "INTEGER"),
            bigquery.SchemaField("q730", "INTEGER"),
            bigquery.SchemaField("q731", "INTEGER"),
            bigquery.SchemaField("q732", "INTEGER"),
            bigquery.SchemaField("q733", "INTEGER"),
            bigquery.SchemaField("q734", "INTEGER"),
            bigquery.SchemaField("q735", "INTEGER"),
            bigquery.SchemaField("q736", "INTEGER"),
            bigquery.SchemaField("q737", "INTEGER"),
            bigquery.SchemaField("q738", "INTEGER"),
            bigquery.SchemaField("q739", "INTEGER"),
            bigquery.SchemaField("q740", "INTEGER"),
            bigquery.SchemaField("q741", "INTEGER"),
            bigquery.SchemaField("q742", "INTEGER"),
            bigquery.SchemaField("q743", "INTEGER"),
            bigquery.SchemaField("q744", "INTEGER"),
            bigquery.SchemaField("q745", "INTEGER"),
            bigquery.SchemaField("q746", "INTEGER"),
            bigquery.SchemaField("q747", "INTEGER"),
            bigquery.SchemaField("q748", "INTEGER"),
            bigquery.SchemaField("q749", "INTEGER"),
            bigquery.SchemaField("q750", "INTEGER"),
            bigquery.SchemaField("q751", "INTEGER"),
            bigquery.SchemaField("q752", "INTEGER"),
            bigquery.SchemaField("q753", "INTEGER"),
            bigquery.SchemaField("q754", "INTEGER"),
            bigquery.SchemaField("q755", "INTEGER"),
            bigquery.SchemaField("q756", "INTEGER"),
            bigquery.SchemaField("q757", "INTEGER"),
            bigquery.SchemaField("q758", "INTEGER"),
            bigquery.SchemaField("q759", "INTEGER"),
            bigquery.SchemaField("q760", "INTEGER"),
            bigquery.SchemaField("q761", "INTEGER"),
            bigquery.SchemaField("q762", "INTEGER"),
            bigquery.SchemaField("q763", "INTEGER"),
            bigquery.SchemaField("q764", "INTEGER"),
            bigquery.SchemaField("q765", "INTEGER"),
            bigquery.SchemaField("q766", "INTEGER"),
            bigquery.SchemaField("q767", "INTEGER"),
            bigquery.SchemaField("q768", "INTEGER"),
            bigquery.SchemaField("q769", "INTEGER"),
            bigquery.SchemaField("q770", "INTEGER"),
            bigquery.SchemaField("q771", "INTEGER"),
            bigquery.SchemaField("q772", "INTEGER"),
            bigquery.SchemaField("q773", "INTEGER"),
            bigquery.SchemaField("q774", "INTEGER"),
            bigquery.SchemaField("q775", "INTEGER"),
            bigquery.SchemaField("q776", "INTEGER"),
            bigquery.SchemaField("q777", "INTEGER"),
            bigquery.SchemaField("q778", "INTEGER"),
            bigquery.SchemaField("q779", "INTEGER"),
            bigquery.SchemaField("q780", "INTEGER"),
            bigquery.SchemaField("q781", "INTEGER"),
            bigquery.SchemaField("q782", "INTEGER"),
            bigquery.SchemaField("q783", "INTEGER"),
            bigquery.SchemaField("q784", "INTEGER"),
            bigquery.SchemaField("q785", "INTEGER"),
            bigquery.SchemaField("q786", "INTEGER"),
            bigquery.SchemaField("q787", "INTEGER"),
            bigquery.SchemaField("q788", "INTEGER"),
            bigquery.SchemaField("q789", "INTEGER"),
            bigquery.SchemaField("q790", "INTEGER"),
            bigquery.SchemaField("q791", "INTEGER"),
            bigquery.SchemaField("q792", "INTEGER"),
            bigquery.SchemaField("q793", "INTEGER"),
            bigquery.SchemaField("q794", "INTEGER"),
            bigquery.SchemaField("q795", "INTEGER"),
            bigquery.SchemaField("q796", "INTEGER"),
            bigquery.SchemaField("q797", "INTEGER"),
            bigquery.SchemaField("q798", "INTEGER"),
            bigquery.SchemaField("q799", "INTEGER"),
            bigquery.SchemaField("q800", "INTEGER"),
            bigquery.SchemaField("q801", "INTEGER"),
            bigquery.SchemaField("q802", "INTEGER"),
            bigquery.SchemaField("q803", "INTEGER"),
            bigquery.SchemaField("q804", "INTEGER"),
            bigquery.SchemaField("q805", "INTEGER"),
            bigquery.SchemaField("q806", "INTEGER"),
            bigquery.SchemaField("q807", "INTEGER"),
            bigquery.SchemaField("q808", "INTEGER"),
            bigquery.SchemaField("q809", "INTEGER"),
            bigquery.SchemaField("q810", "INTEGER"),
            bigquery.SchemaField("q811", "INTEGER"),
            bigquery.SchemaField("q812", "INTEGER"),
            bigquery.SchemaField("q813", "INTEGER"),
            bigquery.SchemaField("q814", "INTEGER"),
            bigquery.SchemaField("q815", "INTEGER"),
            bigquery.SchemaField("q816", "INTEGER"),
            bigquery.SchemaField("q817", "INTEGER"),
            bigquery.SchemaField("q818", "INTEGER"),
            bigquery.SchemaField("q819", "INTEGER"),
            bigquery.SchemaField("q820", "INTEGER"),
            bigquery.SchemaField("q821", "INTEGER"),
            bigquery.SchemaField("q822", "INTEGER"),
            bigquery.SchemaField("q823", "INTEGER"),
            bigquery.SchemaField("q824", "INTEGER"),
            bigquery.SchemaField("q825", "INTEGER"),
            bigquery.SchemaField("q826", "INTEGER"),
            bigquery.SchemaField("q827", "INTEGER"),
            bigquery.SchemaField("q828", "INTEGER"),
            bigquery.SchemaField("q829", "INTEGER"),
            bigquery.SchemaField("q830", "INTEGER"),
            bigquery.SchemaField("q831", "INTEGER"),
            bigquery.SchemaField("q832", "INTEGER"),
            bigquery.SchemaField("q833", "INTEGER"),
            bigquery.SchemaField("q834", "INTEGER"),
            bigquery.SchemaField("q835", "INTEGER"),
            bigquery.SchemaField("q836", "INTEGER"),
            bigquery.SchemaField("q837", "INTEGER"),
            bigquery.SchemaField("q838", "INTEGER"),
            bigquery.SchemaField("q839", "INTEGER"),
            bigquery.SchemaField("q840", "INTEGER"),
            bigquery.SchemaField("q841", "INTEGER"),
            bigquery.SchemaField("q842", "INTEGER"),
            bigquery.SchemaField("q843", "INTEGER"),
            bigquery.SchemaField("q844", "INTEGER"),
            bigquery.SchemaField("q845", "INTEGER"),
            bigquery.SchemaField("q846", "INTEGER"),
            bigquery.SchemaField("q847", "INTEGER"),
            bigquery.SchemaField("q848", "INTEGER"),
            bigquery.SchemaField("q849", "INTEGER"),
            bigquery.SchemaField("q850", "INTEGER"),
            bigquery.SchemaField("q851", "INTEGER"),
            bigquery.SchemaField("q852", "INTEGER"),
            bigquery.SchemaField("q853", "INTEGER"),
            bigquery.SchemaField("q854", "INTEGER"),
            bigquery.SchemaField("q855", "INTEGER"),
            bigquery.SchemaField("q856", "INTEGER"),
            bigquery.SchemaField("q857", "INTEGER"),
            bigquery.SchemaField("q858", "INTEGER"),
            bigquery.SchemaField("q859", "INTEGER"),
            bigquery.SchemaField("q860", "INTEGER"),
            bigquery.SchemaField("q861", "INTEGER"),
            bigquery.SchemaField("q862", "INTEGER"),
            bigquery.SchemaField("q863", "INTEGER"),
            bigquery.SchemaField("q864", "INTEGER"),
            bigquery.SchemaField("q865", "INTEGER"),
            bigquery.SchemaField("q866", "INTEGER"),
            bigquery.SchemaField("q867", "INTEGER"),
            bigquery.SchemaField("q868", "INTEGER"),
            bigquery.SchemaField("q869", "INTEGER"),
            bigquery.SchemaField("q870", "INTEGER"),
            bigquery.SchemaField("q871", "INTEGER"),
            bigquery.SchemaField("q872", "INTEGER"),
            bigquery.SchemaField("q873", "INTEGER"),
            bigquery.SchemaField("q874", "INTEGER"),
            bigquery.SchemaField("q875", "INTEGER"),
            bigquery.SchemaField("q876", "INTEGER"),
            bigquery.SchemaField("q877", "INTEGER"),
            bigquery.SchemaField("q878", "INTEGER"),
            bigquery.SchemaField("q879", "INTEGER"),
            bigquery.SchemaField("q880", "INTEGER"),
            bigquery.SchemaField("q881", "INTEGER"),
            bigquery.SchemaField("q882", "INTEGER"),
            bigquery.SchemaField("q883", "INTEGER"),
            bigquery.SchemaField("q884", "INTEGER"),
            bigquery.SchemaField("q885", "INTEGER"),
            bigquery.SchemaField("q886", "INTEGER"),
            bigquery.SchemaField("q887", "INTEGER"),
            bigquery.SchemaField("q888", "INTEGER"),
            bigquery.SchemaField("q889", "INTEGER"),
            bigquery.SchemaField("q890", "INTEGER"),
            bigquery.SchemaField("q891", "INTEGER"),
            bigquery.SchemaField("q892", "INTEGER"),
            bigquery.SchemaField("q893", "INTEGER"),
            bigquery.SchemaField("q894", "INTEGER"),
            bigquery.SchemaField("q895", "INTEGER"),
            bigquery.SchemaField("q896", "INTEGER"),
            bigquery.SchemaField("q897", "INTEGER"),
            bigquery.SchemaField("q898", "INTEGER"),
            bigquery.SchemaField("q899", "INTEGER"),
            bigquery.SchemaField("q900", "INTEGER"),
            bigquery.SchemaField("q901", "INTEGER"),
            bigquery.SchemaField("q902", "INTEGER"),
            bigquery.SchemaField("q903", "INTEGER"),
            bigquery.SchemaField("q904", "INTEGER"),
            bigquery.SchemaField("q905", "INTEGER"),
            bigquery.SchemaField("q906", "INTEGER"),
            bigquery.SchemaField("q907", "INTEGER"),
            bigquery.SchemaField("q908", "INTEGER"),
            bigquery.SchemaField("q909", "INTEGER"),
            bigquery.SchemaField("q910", "INTEGER"),
            bigquery.SchemaField("q911", "INTEGER"),
            bigquery.SchemaField("q912", "INTEGER"),
            bigquery.SchemaField("q913", "INTEGER"),
            bigquery.SchemaField("q914", "INTEGER"),
            bigquery.SchemaField("q915", "INTEGER"),
            bigquery.SchemaField("q916", "INTEGER"),
            bigquery.SchemaField("q917", "INTEGER"),
            bigquery.SchemaField("q918", "INTEGER"),
            bigquery.SchemaField("q919", "INTEGER"),
            bigquery.SchemaField("q920", "INTEGER"),
            bigquery.SchemaField("q921", "INTEGER"),
            bigquery.SchemaField("q922", "INTEGER"),
            bigquery.SchemaField("q923", "INTEGER"),
            bigquery.SchemaField("q924", "INTEGER"),
            bigquery.SchemaField("q925", "INTEGER"),
            bigquery.SchemaField("q926", "INTEGER"),
            bigquery.SchemaField("q927", "INTEGER"),
            bigquery.SchemaField("q928", "INTEGER"),
            bigquery.SchemaField("q929", "INTEGER"),
            bigquery.SchemaField("q930", "INTEGER"),
            bigquery.SchemaField("q931", "INTEGER"),
            bigquery.SchemaField("q932", "INTEGER"),
            bigquery.SchemaField("q933", "INTEGER"),
            bigquery.SchemaField("q934", "INTEGER"),
            bigquery.SchemaField("q935", "INTEGER"),
            bigquery.SchemaField("q936", "INTEGER"),
            bigquery.SchemaField("q937", "INTEGER"),
            bigquery.SchemaField("q938", "INTEGER"),
            bigquery.SchemaField("q939", "INTEGER"),
            bigquery.SchemaField("q940", "INTEGER"),
            bigquery.SchemaField("q941", "INTEGER"),
            bigquery.SchemaField("q942", "INTEGER"),
            bigquery.SchemaField("q943", "INTEGER"),
            bigquery.SchemaField("q944", "INTEGER"),
            bigquery.SchemaField("q945", "INTEGER"),
            bigquery.SchemaField("q946", "INTEGER"),
            bigquery.SchemaField("q947", "INTEGER"),
            bigquery.SchemaField("q948", "INTEGER"),
            bigquery.SchemaField("q949", "INTEGER"),
            bigquery.SchemaField("q950", "INTEGER"),
            bigquery.SchemaField("q951", "INTEGER"),
            bigquery.SchemaField("q952", "INTEGER"),
            bigquery.SchemaField("q953", "INTEGER"),
            bigquery.SchemaField("q954", "INTEGER"),
            bigquery.SchemaField("q955", "INTEGER"),
            bigquery.SchemaField("q956", "INTEGER"),
            bigquery.SchemaField("q957", "INTEGER"),
            bigquery.SchemaField("q958", "INTEGER"),
            bigquery.SchemaField("q959", "INTEGER"),
            bigquery.SchemaField("q960", "INTEGER"),
            bigquery.SchemaField("q961", "INTEGER"),
            bigquery.SchemaField("q962", "INTEGER"),
            bigquery.SchemaField("q963", "INTEGER"),
            bigquery.SchemaField("q964", "INTEGER"),
            bigquery.SchemaField("q965", "INTEGER"),
            bigquery.SchemaField("q966", "INTEGER"),
            bigquery.SchemaField("q967", "INTEGER"),
            bigquery.SchemaField("q968", "INTEGER"),
            bigquery.SchemaField("q969", "INTEGER"),
            bigquery.SchemaField("q970", "INTEGER"),
            bigquery.SchemaField("q971", "INTEGER"),
            bigquery.SchemaField("q972", "INTEGER"),
            bigquery.SchemaField("q973", "INTEGER"),
            bigquery.SchemaField("q974", "INTEGER"),
            bigquery.SchemaField("q975", "INTEGER"),
            bigquery.SchemaField("q976", "INTEGER"),
            bigquery.SchemaField("q977", "INTEGER"),
            bigquery.SchemaField("q978", "INTEGER"),
            bigquery.SchemaField("q979", "INTEGER"),
            bigquery.SchemaField("q980", "INTEGER"),
            bigquery.SchemaField("q981", "INTEGER"),
            bigquery.SchemaField("q982", "INTEGER"),
            bigquery.SchemaField("q983", "INTEGER"),
            bigquery.SchemaField("q984", "INTEGER"),
            bigquery.SchemaField("q985", "INTEGER"),
            bigquery.SchemaField("q986", "INTEGER"),
            bigquery.SchemaField("q987", "INTEGER"),
            bigquery.SchemaField("q988", "INTEGER"),
            bigquery.SchemaField("q989", "INTEGER"),
            bigquery.SchemaField("q990", "INTEGER"),
            bigquery.SchemaField("q991", "INTEGER"),
            bigquery.SchemaField("q992", "INTEGER"),
            bigquery.SchemaField("q993", "INTEGER"),
            bigquery.SchemaField("q994", "INTEGER"),
            bigquery.SchemaField("q995", "INTEGER"),
            bigquery.SchemaField("q996", "INTEGER"),
            bigquery.SchemaField("q997", "INTEGER"),
            bigquery.SchemaField("q998", "INTEGER"),
            bigquery.SchemaField("q999", "INTEGER"),
            bigquery.SchemaField("q1000", "INTEGER"),
            bigquery.SchemaField("q1001", "INTEGER"),
            bigquery.SchemaField("q1002", "INTEGER"),
            bigquery.SchemaField("q1003", "INTEGER"),
            bigquery.SchemaField("q1004", "INTEGER"),
            bigquery.SchemaField("q1005", "INTEGER"),
            bigquery.SchemaField("q1006", "INTEGER"),
            bigquery.SchemaField("q1007", "INTEGER"),
            bigquery.SchemaField("q1008", "INTEGER"),
            bigquery.SchemaField("q1009", "INTEGER"),
            bigquery.SchemaField("q1010", "INTEGER"),
            bigquery.SchemaField("q1011", "INTEGER"),
            bigquery.SchemaField("q1012", "INTEGER"),
            bigquery.SchemaField("q1013", "INTEGER"),
            bigquery.SchemaField("q1014", "INTEGER"),
            bigquery.SchemaField("q1015", "INTEGER"),
            bigquery.SchemaField("q1016", "INTEGER"),
            bigquery.SchemaField("q1017", "INTEGER"),
            bigquery.SchemaField("q1018", "INTEGER"),
            bigquery.SchemaField("q1019", "INTEGER"),
            bigquery.SchemaField("q1020", "INTEGER"),
            bigquery.SchemaField("q1021", "INTEGER"),
            bigquery.SchemaField("q1022", "INTEGER"),
            bigquery.SchemaField("q1023", "INTEGER"),
            bigquery.SchemaField("q1024", "INTEGER"),
            bigquery.SchemaField("q1025", "INTEGER"),
            bigquery.SchemaField("q1026", "INTEGER"),
            bigquery.SchemaField("q1027", "INTEGER"),
            bigquery.SchemaField("q1028", "INTEGER"),
            bigquery.SchemaField("q1029", "INTEGER"),
            bigquery.SchemaField("q1030", "INTEGER"),
            bigquery.SchemaField("q1031", "INTEGER"),
            bigquery.SchemaField("q1032", "INTEGER"),
            bigquery.SchemaField("q1033", "INTEGER"),
            bigquery.SchemaField("q1034", "INTEGER"),
            bigquery.SchemaField("q1035", "INTEGER"),
            bigquery.SchemaField("q1036", "INTEGER"),
            bigquery.SchemaField("q1037", "INTEGER"),
            bigquery.SchemaField("q1038", "INTEGER"),
            bigquery.SchemaField("q1039", "INTEGER"),
            bigquery.SchemaField("q1040", "INTEGER"),
            bigquery.SchemaField("q1041", "INTEGER"),
            bigquery.SchemaField("q1042", "INTEGER"),
            bigquery.SchemaField("q1043", "INTEGER"),
            bigquery.SchemaField("q1044", "INTEGER"),
            bigquery.SchemaField("q1045", "INTEGER"),
            bigquery.SchemaField("q1046", "INTEGER"),
            bigquery.SchemaField("q1047", "INTEGER"),
            bigquery.SchemaField("q1048", "INTEGER"),
            bigquery.SchemaField("q1049", "INTEGER"),
            bigquery.SchemaField("q1050", "INTEGER"),
            bigquery.SchemaField("q1051", "INTEGER"),
            bigquery.SchemaField("q1052", "INTEGER"),
            bigquery.SchemaField("q1053", "INTEGER"),
            bigquery.SchemaField("q1054", "INTEGER"),
            bigquery.SchemaField("q1055", "INTEGER"),
            bigquery.SchemaField("q1056", "INTEGER"),
            bigquery.SchemaField("q1057", "INTEGER"),
            bigquery.SchemaField("q1058", "INTEGER"),
            bigquery.SchemaField("q1059", "INTEGER"),
            bigquery.SchemaField("q1060", "INTEGER"),
            bigquery.SchemaField("q1061", "INTEGER"),
            bigquery.SchemaField("q1062", "INTEGER"),
            bigquery.SchemaField("q1063", "INTEGER"),
            bigquery.SchemaField("q1064", "INTEGER"),
            bigquery.SchemaField("q1065", "INTEGER"),
            bigquery.SchemaField("q1066", "INTEGER"),
            bigquery.SchemaField("q1067", "INTEGER"),
            bigquery.SchemaField("q1068", "INTEGER"),
            bigquery.SchemaField("q1069", "INTEGER"),
            bigquery.SchemaField("q1070", "INTEGER"),
            bigquery.SchemaField("q1071", "INTEGER"),
            bigquery.SchemaField("q1072", "INTEGER"),
            bigquery.SchemaField("q1073", "INTEGER"),
            bigquery.SchemaField("q1074", "INTEGER"),
            bigquery.SchemaField("q1075", "INTEGER"),
            bigquery.SchemaField("q1076", "INTEGER"),
            bigquery.SchemaField("q1077", "INTEGER"),
            bigquery.SchemaField("q1078", "INTEGER"),
            bigquery.SchemaField("q1079", "INTEGER"),
            bigquery.SchemaField("q1080", "INTEGER"),
            bigquery.SchemaField("q1081", "INTEGER"),
            bigquery.SchemaField("q1082", "INTEGER"),
            bigquery.SchemaField("q1083", "INTEGER"),
            bigquery.SchemaField("q1084", "INTEGER"),
            bigquery.SchemaField("q1085", "INTEGER"),
            bigquery.SchemaField("q1086", "INTEGER"),
            bigquery.SchemaField("q1087", "INTEGER"),
            bigquery.SchemaField("q1088", "INTEGER"),
            bigquery.SchemaField("q1089", "INTEGER"),
            bigquery.SchemaField("q1090", "INTEGER"),
            bigquery.SchemaField("q1091", "INTEGER"),
            bigquery.SchemaField("q1092", "INTEGER"),
            bigquery.SchemaField("q1093", "INTEGER"),
            bigquery.SchemaField("q1094", "INTEGER"),
            bigquery.SchemaField("q1095", "INTEGER"),
            bigquery.SchemaField("q1096", "INTEGER"),
            bigquery.SchemaField("q1097", "INTEGER"),
            bigquery.SchemaField("q1098", "INTEGER"),
            bigquery.SchemaField("q1099", "INTEGER"),
            bigquery.SchemaField("q1100", "INTEGER"),
            bigquery.SchemaField("q1101", "INTEGER"),
            bigquery.SchemaField("q1102", "INTEGER"),
            bigquery.SchemaField("q1103", "INTEGER"),
            bigquery.SchemaField("q1104", "INTEGER"),
            bigquery.SchemaField("q1105", "INTEGER"),
            bigquery.SchemaField("q1106", "INTEGER"),
            #does not exist
            #bigquery.SchemaField("q1107", "INTEGER"),
            bigquery.SchemaField("q1108", "INTEGER"),
            bigquery.SchemaField("q1109", "INTEGER"),
            bigquery.SchemaField("q1110", "INTEGER"),
            bigquery.SchemaField("q1111", "INTEGER"),
            bigquery.SchemaField("q1112", "INTEGER"),
            bigquery.SchemaField("q1113", "INTEGER"),
            bigquery.SchemaField("q1114", "INTEGER"),
            bigquery.SchemaField("q1115", "INTEGER"),
            bigquery.SchemaField("q1116", "INTEGER"),
            bigquery.SchemaField("q1117", "INTEGER"),
            bigquery.SchemaField("q1118", "INTEGER"),
            bigquery.SchemaField("q1119", "INTEGER"),
            bigquery.SchemaField("q1120", "INTEGER"),
            bigquery.SchemaField("q1121", "INTEGER"),
            bigquery.SchemaField("q1122", "INTEGER"),
            bigquery.SchemaField("q1123", "INTEGER"),
            bigquery.SchemaField("q1124", "INTEGER"),
            bigquery.SchemaField("q1125", "INTEGER"),
            bigquery.SchemaField("q1126", "INTEGER"),
            bigquery.SchemaField("q1127", "INTEGER"),
            bigquery.SchemaField("q1128", "INTEGER"),
            bigquery.SchemaField("q1129", "INTEGER"),
            bigquery.SchemaField("q1130", "INTEGER"),
            bigquery.SchemaField("q1131", "INTEGER"),
            bigquery.SchemaField("q1132", "INTEGER"),
            bigquery.SchemaField("q1133", "INTEGER"),
            bigquery.SchemaField("q1134", "INTEGER"),
            bigquery.SchemaField("q1135", "INTEGER"),
            bigquery.SchemaField("q1136", "INTEGER"),
            bigquery.SchemaField("q1137", "INTEGER"),
            bigquery.SchemaField("q1138", "INTEGER"),
            bigquery.SchemaField("q1139", "INTEGER"),
            bigquery.SchemaField("q1140", "INTEGER"),
            bigquery.SchemaField("q1141", "INTEGER"),
            bigquery.SchemaField("q1142", "INTEGER"),
            bigquery.SchemaField("q1143", "INTEGER"),
            bigquery.SchemaField("q1144", "INTEGER"),
            bigquery.SchemaField("q1145", "INTEGER"),
            bigquery.SchemaField("q1146", "INTEGER"),
            bigquery.SchemaField("q1147", "INTEGER"),
            bigquery.SchemaField("q1148", "INTEGER"),
            bigquery.SchemaField("q1149", "INTEGER"),
            bigquery.SchemaField("q1150", "INTEGER"),
            bigquery.SchemaField("q1151", "INTEGER"),
            bigquery.SchemaField("q1152", "INTEGER"),
            bigquery.SchemaField("q1153", "INTEGER"),
            bigquery.SchemaField("q1154", "INTEGER"),
            bigquery.SchemaField("q1155", "INTEGER"),
            bigquery.SchemaField("q1156", "INTEGER"),
            bigquery.SchemaField("q1157", "INTEGER"),
            bigquery.SchemaField("q1158", "INTEGER"),
            bigquery.SchemaField("q1159", "INTEGER"),
            bigquery.SchemaField("q1160", "INTEGER"),
            bigquery.SchemaField("q1161", "INTEGER"),
            bigquery.SchemaField("q1162", "INTEGER"),
            bigquery.SchemaField("q1163", "INTEGER")
        ],
        # Set job configuration write_disposition to be able to overwrite existing table
    write_disposition='WRITE_TRUNCATE'
    )

    # Define job
job = client.load_table_from_dataframe(
    muse_model_df,
    table_id,
    job_config=job_config,
    location='US'
)

    # Wait for the load job to complete.
job.result()
    
    # Make an API request
table = client.get_table(table_id)
print(
    'Loaded {} rows with {} columns to {}'.format(table.num_rows, len(table.schema), table_id)
    )

KeyError: 'q1'